   - name: Copy SetupOptions Jar File to remote location
     copy: src="{{playbook_dir}}/library/" dest="{{vex.install_location}}lib/"
     # when: vex.server_share_path is defined     
   
   - name: Configure Shares in Remote Machines
     shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{vex.dname}}" "{{vex.install_location}}" "SHARE" "{{vex.custom_macro}}"
     environment:
       CLASSPATH: ":{{vex.install_location}}*.jar:{{vex.install_location}}lib/*:{{vex.install_location}}lib/help/*:{{vex.install_location}}lib/hibernate/*:{{vex.install_location}}lib/secureshare/*:{{vex.install_location}}webserver/AjaxSwing/lib/*:{{vex.install_location}}lib/json/*"
     args:
       chdir: "{{vex.install_location}}"
     # with_dict: "{{configure_apps['nfs_server_shares'] | default({}) }}"
     # when: (vex.name != 'VLProxy' and vex.server_share_path is defined)
     register: shares_config
     retries: 3
     delay: 5  
     until: shares_config|success

   - name: Creates Shares  Directory
     file: path="{{vex.client_local_path}}" state=directory

   # - name: Set IP address of Shares
     # set_fact:
        # share_ipaddr: "{{ hostvars[groups['shares'][0]]['ansible_eth0']['ipv4']['address'] }}"
     # delegate_to: 127.0.0.1
     
   # - name: Print share ip hostvars
     # debug: msg="share ip addre {{ share_ipaddr }}" 
     # delegate_to: 127.0.0.1
     
   - name: Setup Shares in Client boxes
     mount:
       name: "{{vex.client_local_path}}"
       src: "{{hostvars['servers-shares-1']['ansible_eth0']['ipv4']['address'] }}:{{item.value.server_share_path}}"
       state: mounted
       fstype: "nfs"     
     #with_dict: "{{configure_apps['nfs_client_shares'] | default({}) }}"
     with_dict: "{{ shares }}"
     register: shares_client
     retries: 3
     delay: 5
     until: shares_client|success     