---
# tasks file for configure.product
- block:
   - name: Setting Dictionary Name for Client Share
     set_fact:
        vexcli: "{{clishare.value}}"

   - name: Configure Client Side Shares
     include: "configure_client_share.yml"             
          
    # - name: Configure Client Side Shares
      # include: "configure_client_share.yml"
      # with_dict: "{{ versalex | default({}) }}"
      # loop_control:
          # loop_var: clishare     
  rescue:
      - fail: msg="Configure Client Share failed"