---
# tasks file for setup.sync

   - name: Include Configure Product Role with Versalex
     include_tasks: setup_sync.yml
     with_dict: "{{ versalex | default({}) }}"
     loop_control:
        loop_var: group_item

