---
# tasks file for setup.sync
   - name: Setting Dictionary Name for Proxy Inside
     set_fact:
        syncgrp: "{{group_item.value}}"

   - name: Create Node JSON Dir
     file:
        path: "{{playbook_dir}}/files/sync_json/"
        state: directory
     delegate_to: 127.0.0.1   
     when: play_hosts.index(inventory_hostname) > 0        
        
   - name: Create Node JSON file for Each Host
     template:
        src: "node.json.j2"
        dest: "{{playbook_dir}}/files/sync_json/{{inventory_hostname}}.json"
     delegate_to: 127.0.0.1   
     when: play_hosts.index(inventory_hostname) > 0   

   - set_fact:
        sync_serials: []
     delegate_to: 127.0.0.1
     
   - set_fact:
        node_serials: "{{ lookup('file','{{playbook_dir}}/files/sync_json/{{inventory_hostname}}.json')|from_json }}"     
     # with_fileglob: "{{playbook_dir}}/files/sync_json/*.json" 
     when: play_hosts.index(inventory_hostname) > 0
     delegate_to: 127.0.0.1   

   - set_fact:
        sync_serials: "{{ sync_serials }} + [ '{{ hostvars[item]['node_serials']['serial'] }}' ]"
     with_items: "{{ groups[ 'servers-versalex' ] | default([]) }}"
     when: (play_hosts.index(inventory_hostname) == 0 and play_hosts.index(item) > 0)
     delegate_to: 127.0.0.1   
     

   - debug: msg="Serial Lists-{{sync_serials}}"
     when: play_hosts.index(inventory_hostname) == 0
     delegate_to: 127.0.0.1  
     
   - name: Setup Sync Using REST-Add Node
     uri:
        url: "http://{{ansible_ssh_host}}:5080/api/nodes?username=administrator&password=Admin"
        method: POST
        user: administrator
        password: Admin
        body_format: json
        body: "{{ lookup('file','{{item}}') }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 201
     register: rest_addnode
     with_fileglob: "{{playbook_dir}}/files/sync_json/*.json" 
     when:  play_hosts.index(inventory_hostname) == 0
     retries: 1
     delay: 5  
     until: rest_addnode|success
     delegate_to: 127.0.0.1
     ignore_errors: yes


   - name: Setup Sync Using REST-Initialize
     uri:
        url: "http://{{ansible_ssh_host}}:5080/api/nodes/{{item}}/initialize"
        method: POST
        user: administrator
        password: Admin
        force_basic_auth: yes
        return_content: yes
        status_code: 200
        headers:
            Content-Type: "application/json"
     register: init_status
     when: play_hosts.index(inventory_hostname) == 0
     with_items: "{{sync_serials}}" 
     retries: 3
     delay: 5  
     until: init_status|success
     delegate_to: 127.0.0.1     
     
     
   # - name: Kill Harmony Processes Karaf and OSGI
     # shell: "kill -9 $(ps -aef |grep 'karaf.main' |grep -v grep |awk '{print $2 \"\t\" $3}')"
     # register: kill_status        
     # ignore_errors: yes
     
   # - name: Print Kill Details
     # debug: msg="Kll Details:{{kill_status}}"     
   
   # - name: Remove schedule Lock File if exists
     # file:
         # path: "{{syncgrp.install_location}}schedule.lck"
         # state: absent
     # ignore_errors: yes
   # # - name: Wait for port 5080 to get Stopped
     # # wait_for: host="{{inventory_hostname}}" port="{{syncgrp.port}}" delay=20 state=stopped

   # - name: Start VersalEx Product Daemon   
     # shell: "{{item}}"
     # args:
       # chdir: "{{syncgrp.install_location}}"
     # with_items:
       # - ./{{syncgrp.dname}}d start
     # register: startvexstatus

   # - name: Wait for port 5080 to get Started
     # wait_for: host="{{inventory_hostname}}" port="{{syncgrp.port}}" delay=20 state=started
               
     
     
