---
# tasks file for install.apps
- name: Install Unzip package for running bin file in CentOS
  yum: name=unzip state=present
          
- name: Install libxslt-devel package for running bin file in CentOS
  yum: name="{{item}}" state=present
  with_items:
        - libxml2 
        - libxml2-devel
        - libxslt
        - libxslt-devel
        - python-devel
        
# - name: Install python-devel package for running bin file in CentOS
  # yum: name=python-devel state=present
  
# - name: Install Development tools package
  # yum: name="@Development tools" state=present
   
- name: "Install python-lxml packages(required for maven_artifact) on CentOS or Redhat machines"
  yum: name=python-lxml state=present
  retries: 3
  delay: 5  
  until: install_lxml|success
  register: install_lxml

- name: Checking Python 2.7 available or not in Linux Systems
  shell: python --version
  register: py_version
  
- debug: msg="Pre Tasks Completed::{{py_version}}"  
# - name: "Install python2.7 in OS if python 3 is default"
  # include: "install_centos_py27.yml"
  # when: ansible_distribution_version | int >= 9

- name: Install EPEL Repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
  state: present

- name: Install Pip using YUM
  yum: name=python-pip state=present 
      
- name: Install using pip
  shell: pip install --upgrade lxml
  register: pyver

- name: Update /etc/hosts from inventory
  lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
  with_items: '{{groups.all}}'
  
- name: Install RNG-tools required for Random Number Generation using YUM
  yum: name=rng-tools state=present
  
- name: Run RNGD Service
  service: name=rngd state=restarted
  register: rngd_status
  retries: 3
  delay: 10
  until: rngd_status|success