---
# tasks file for versalex.apps
 - block:
   - name: Setting Dictionary Name for Versalex Inside
     set_fact:
        versalex: "{{group_item.value}}"

   - name: Install CentOS Related Dependencies 
     include: centos.yml
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'     

   - name: Install Debian Related Dependencies
     include: debian.yml
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: Creates Install Location Directory
     file: path="{{versalex.install_location}}" state=directory force=yes
     when: versalex.name is defined
     
   # - name: Debug MSGS
     # debug: msg="Install Loc {{versalex.install_location}} "
     # when: versalex.name is defined
     
   - include: "download_versalex.yml"
     when: versalex.name is defined
     delegate_to: 127.0.0.1
     # run_once: true
 
   - name: Generate License Keys in Each Node
     include: "setup_vexlicense.yml"
     when: versalex.name is defined and versalex.name |lower != 'vlproxy'      
      
   - name: "Install Versalex (Non Dockerized Install)"    
     include: "install_versalex.yml"
     register: install_status
     retries: 3
     delay: 5  
     until: install_status|success
     when: versalex.name is defined
     
   - name: Print Last Include Task Results
     debug: msg="Install_status results {{install_status}}"
   # - name: Call Create VLProxy File
     # include: "create_vlproxyfile.yml"
     # when: versalex.name != 'VLProxy' 
     # delegate_to: 127.0.0.1
   rescue:
   - fail: msg="Install Apps failed Non Docker"
     when: item.failed==true
     with_items: "{{ install_status.results }}"