---
- name: "Install Yum centos-release-scl for python2.7 install"
  yum: name=centos-release-scl state=present
  
- name: "Install Python 2.7 using Yum"
  yum: name=python27 state=present

- name: Check Version of python2.7
  command: "python --version"
  register: python_check
  
- name: Python Version
  debug: msg="Python Version{{python_check}}"
  
- name: Install openssl-devel present
  yum: name=openssl-devel state=present
 
# - name: Check Version of python2.7
  # command: "python --version"
  # register: python_check
  # ignore_errors: True
  # changed_when: False
  # environment:
    # PATH: "/usr/local/bin:/usr/bin:{{ (ansible_env|default({})).PATH|default('') }}"
    
# - name: download python2.7 source
  # get_url:
    # url: http://python.org/ftp/python/2.7.5/Python-2.7.5.tar.bz2
    # dest: /tmp/Python-2.7.5.tar.bz2
    # timeout: 30

# - name: unpack python2.7 source
  # unarchive:
    # src: /tmp/Python-2.7.5.tar.bz2
    # dest: /tmp
    # copy: no

# - name: install python2.7 from source
  # shell: ./configure --prefix=/usr/local && make && make altinstall
  # args:
    # chdir: /tmp/Python-2.7.5

# - name: create symlink in /usr/bin
  # alternatives:
    # name: "python2.7"
    # link: /usr/local/bin/python
    # path: /usr/local/bin/python2.7
    
# - name: download setuptools
  # get_url:
    # url: https://bootstrap.pypa.io/ez_setup.py
    # dest: /tmp/ez_setup.py
    # timeout: 30

# - name: install setuptools
  # command: "/usr/bin/python ez_setup.py --version=19.6.2"
  # args: { chdir: /tmp }

# - name: install pip
  # easy_install: name=pip executable=easy_install-2.7
  # environment:
    # PATH: "/usr/local/bin:/usr/bin:{{ (ansible_env|default({})).PATH|default('') }}"