---
# tasks file for download.product
- block:
   - name: Install Product  with Versalex
     include: "install_versalex.yml"
     with_dict: "{{ prod_dict | default({}) }}"
     when: prod_dict is defined        
     loop_control:
        loop_var: group_item  
  rescue:
      - fail: msg="Installing Product Tasks failed"