---
   - name: Start VersalEx Process After Install
     shell: "./{{versalex.dname}}d start"
     args:
      chdir: "{{versalex.install_location}}"     
     when: installres|changed
     register: vex_start_status
     
   - name: Wait for Versalex Port to Come up
     wait_for: host="{{ansible_ssh_host}}" port="{{versalex.port}}" delay=10 timeout=320 state=started
     when: vex_start_status|changed and versalex.dname != 'VLProxy'