---
   # - name: Install lxml using pip Locally in Container
     # pip: 
        # name: lxml
     # delegate_to: 127.0.0.1
    
  - name: Download Versalex Bin Package from Nexus Central with Run Once enabled
    maven_artifact:
        group_id: "com.cleo.ep"
        artifact_id: "password-hasher"
        version: latest
        classifier: ""
        extension: "jar"
        repository_url: "{{versalex.nexus_prod_repourl}}"
        dest: "{{playbook_dir}}/library/password-hasher.jar"
        state: present
    delegate_to: 127.0.0.1         
  
  - name: Copy VLNavigator Admin password jar to Remote
    copy: src="{{playbook_dir}}/library/password-hasher.jar" dest="{{versalex.install_location}}lib/password-hasher.jar"

  - name: Generate Hashed Password  for VLNavigator
    shell: jre/bin/java -cp $CLASSPATH com.cleo.ep.PasswordHasher 'Admin'
    environment:
       CLASSPATH: ":{{versalex.install_location}}*.jar:{{versalex.install_location}}lib/*:"    
    args:
       chdir: "{{ versalex.install_location }}"
    register: password_hasher
    
  - set_fact: hashed_admin_pwd="{{ password_hasher.stdout }}"    
    
  - name: Generate Users xml for Admin Setup
    template:
        src: "{{ item }}.j2"
        dest: "{{ versalex.install_location }}/conf/{{ item }}"
    with_items:
        - Users.xml
    