---
# tasks file for setup.testprofiles
- block:
   - name: Setting Dictionary Name for Proxy Inside
     set_fact:
        versalex: "{{group_item.value}}"

   - name: Configure DataSet in TP Side Nodes
     include: "configure_tp.yml"
     with_dict: "{{ dataset | default({}) }}"
     loop_control:
        loop_var: conf_dataset
     
   - name: Print Debug Msgs Setup Flow
     debug: msg="Done with Setup Flow"   
- rescue:
   - fail: msg="Setup Test Profile Module Failed" 
