---
    - name: Print TP Node IPS to Setup Test Profiles
      debug: msg="Print IP Addr-{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
      delegate_to: 127.0.0.1
      
    - name: Set Dataset fact for TPNodes
      set_fact:
            tp_dataset: "{{hostvars['servers-versalex-1']['dataset']}}"
      when: "'tpnodes-versalex' in inventory_hostname"      
      delegate_to: 127.0.0.1

    - name: Print Client Args TP Dataset111
      debug: msg="Client Args Meta Result{{tp_dataset}}"      
      when: "'tpnodes-versalex' in inventory_hostname"
      delegate_to: 127.0.0.1
      
    - name: Setup FTP Client Args
      setup_ftp_client_args:
        host_ip: "{{ansible_ssh_host}}"
        server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        proxy_hosts: "{{ groups['servers-proxy'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        tp_hosts: "{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        dataset: "{{tp_dataset}}"
      when: "'tpnodes-versalex' in inventory_hostname"
      register: ftp_client_args
      delegate_to: 127.0.0.1
      
    - name: Print Client Args 
      debug: msg="Client Args Meta Result{{ftp_client_args}}"
      
    - name: Setup Testprofiles in TP Side Nodes
      include_tasks: setup_flow.yml
      with_dict: "{{ versalex | default({}) }}"
      when: "'tpnodes-versalex' in inventory_hostname"
      loop_control:
         loop_var: ftp_client
      delegate_to: 127.0.0.1
      
    # - name: Setup FTP Client Profiles using Rest
      # setup_ftp_client:
        # host_name: "{{hostname}}"
        # server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        # proxy_hosts: "{{ groups['servers-proxy'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        # tp_hosts: "{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        # dataset: "{{dataset}}"
      # # when: "'servers-versalex-1' in inventory_hostname"
      # register: rest_status      
      # delegate_to: 127.0.0.1
          
    # - name: Debug Rest Details
      # debug: msg="Rest Details{{rest_status}}"
      # delegate_to: 127.0.0.1