---
# tasks file for setup.testprofiles
- block:
   - name: Setting Dictionary Name for Proxy Inside
     set_fact:
        tp_profile: "{{ftp_client.value}}"

   - name: Configure DataSet in TP Side Nodes
     include_tasks: "configure_tp.yml"
     # with_dict: "{{dataset | default({}) }}"
     # loop_control:
        # loop_var: tp_ftp
     
   - name: Print Debug Msgs Setup Flow
     debug: msg="Done with Setup Flow"   
- rescue:
   - fail: msg="Setup Test Profile Module Failed" 
