---
   - name: Print Hostvars
     debug: msg="Versalex name{{versalex.name}}"     

   - name: Copy SetupOptions Jar File to remote location
     copy: src="/root/workspace/EFSS/non-shipped/test/automation/systemtesting/setup_versalex/target/systest_jars-0.1-SNAPSHOT.jar" dest="{{versalex.install_location}}/SetupTestProfile.jar"

   - name: Set Dataset key
     set_fact:
          ds_key: "{{conf_dataset.key}}"
   
   - name: Configure Test Profiles in Remote Machines for Server Side
     shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupTestProfile "{{versalex.name}}" "{{versalex.install_location}}" "{{item.name}}" "{{item.hr}}" "{{item.mailbox_range}}" "{{item.action_range}}" "{{ item.ip }}" "5080"  "" "{{item.host_custom_props}}" "{{item.mailbox_custom_props}}" "{{item.action_custom_props}}" "{{item.create_certs}}"
     environment:
       CLASSPATH: ":{{versalex.install_location}}SetupTestProfile.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
     args:
       executable: /bin/sh
       chdir: "{{versalex.install_location}}"
     with_items: "{{dataset[ds_key]}}"          
     register: profile_config
     # when: vex_product  is defined and vex_product != 'VLProxy' and node_type == 'Sender'
#   - name: Print Profile Config Details
#     debug: msg="Profile Details:{{profile_config}}"
#     when: vex_product  is defined and vex_product != 'VLProxy' and node_type == 'Sender'
   - name: Copy Certs from Remote Locaton to Local
     synchronize: src="{{versalex.install_location}}systestcerts"  dest="{{playbook_dir}}/res/" mode=pull
     # when: node_type == 'Sender'
     register: copy_status
     until: copy_status|success
     retries: 3
     delay: 10
     