---
# tasks file for setup.testprofiles
- block:
   - name: "Validate all hosts synced in server nodes"
     include_tasks: "check_unsynced.yml"
     with_dict: "{{ versalex | default({}) }}"
     loop_control:
        loop_var: check_unsync

   - name: Printing for Debug
     debug: msg="Done with Updating Properties "
     delegate_to: 127.0.0.1
- rescue:
   - fail: msg="Setup Test Profile Module Failed"