---
- name: Setting Dictionary Name JMX Configs Versalex
  set_fact:
        vex_db: "{{config_db.value}}"
        
- name: Download DB artifact from Maven Central
  maven_artifact:
    repository_url: "{{item.value.repository_url}}"
    group_id: "{{item.value.maven_groupid}}"
    artifact_id: "{{item.value.maven_artifactid}}"
    version: "{{item.value.maven_version}}"
    dest: "{{vex_db.install_location}}lib/ext/"  
  when: "'db' in item.value.type"  
  with_dict: "{{ integrations | default({}) }}"
  register: mysql_download
  ignore_errors: yes
  register: maven_db
  retries: 2
  delay: 5  
  until: maven_db|success
        
- name: Extract DB IP 
  set_fact:
    db_ip: "{{ groups['integrations'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
  when: "'db' in item.value.type"
  with_dict: "{{ integrations | default({}) }}"  
  delegate_to: 127.0.0.1
  register: db_ip_status
  retries: 2
  delay: 5  
  until: db_ip_status|success
  
- name: Configure DB in Remote Machines
  shell: jre/bin/java -cp "$CLASSPATH" com.cleo.systest.SetupOptions "{{vex_db.dname}}" "{{vex_db.install_location}}" "DB" "jdbc:{{item.value.app_type}}://{{db_ip}}:{{item.value.port}}/{{item.value.dbname}}" "{{item.value.driver_str}}" "{{item.value.username}}" "{{item.value.password}}" 1 "jdbc:{{item.value.app_type}}://{{db_ip}}:{{item.value.port}}/{{item.value.dbname}}"
  environment:
     CLASSPATH: ":lib/versalex_setup-latest.jar:lib/*:lib/api/connector/*:lib/aws/*:lib/connector/*:lib/docdb/*:lib/hadoop/*:lib/help/*:lib/hibernate/*:lib/jersey/*:lib/json/*:lib/saml/*:lib/scim/*:lib/secureshare/*:lib/uri/*:lib/vaadin/*:lib/validator/*:lib/ws/*:webserver/AjaxSwing/lib/ajaxswing.jar:webserver/AjaxSwing/lib/commons-fileupload-1.0.jar:webserver/AjaxSwing/lib/freemarker.jar:webserver/AjaxSwing/lib/jsonrpc-1.0.jar:webserver/AjaxSwing/lib/boot/asboot.jar:webserver/AjaxSwing/lib/install/asm-all-3.1.jar:lax.jar"
  args:
     chdir: "{{vex_db.install_location}}"
  when: "'db' in item.value.type"
  with_dict: "{{ integrations | default({}) }}"  
  register: db_config
  retries: 2
  delay: 5  
  until: db_config|success
  