---
# tasks file for setup.testprofiles
- block:
   - name: Set macro name if defined
     set_fact: 
        macro_name: "%datashare%"
     when: shares is defined

   - name: Setup Omni Users Hosts and Mailbox for FTP on Server
     setup_omni_users:
       host_name: "{{hostname}}"
       server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
       proxy_hosts: "{{ groups['servers-proxy'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
       tp_hosts: "{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
       dataset: "{{dataset |default({})}}"
       host_type: "ftp"
       default_home_dir: "{{macro_name}}"
     register: omni_ftp_users
     when: (play_hosts.index(inventory_hostname) == 0)      
     delegate_to: 127.0.0.1

   - name: Printing for Debug
     debug: msg="Done with Server Side DataSet Configs {{omni_ftp_users}}"  
  
   # - name: Setup Testprofiles in Server Side Nodes for SSHFTP
     # include_tasks: configure_server.yml
     # with_dict: "{{ versalex | default({}) }}"
     # when: "'servers-versalex-1' in inventory_hostname"
     # loop_control:
        # loop_var: group_ftp

- rescue:
   - fail: msg="Setup Test Profile Module FTP Failed"     