---
# tasks file for setup.testprofiles
- block:
   - name: Setting Group Name
     set_fact:        
       grp_name: 'tpnodes-versalex'
     delegate_to: 127.0.0.1

   - name: Setting Node Count for TPNodes
     set_fact:        
       vex_count: "{{ groups[grp_name] | length | int}}"
     delegate_to: 127.0.0.1
     
   - name: TestProfile map for ServerSide
     template: src=setup_tp_testprofile.j2 dest="{{playbook_dir}}/dataset/{{inventory_hostname}}-{{grp_name}}.yml"
     delegate_to: 127.0.0.1

   - name: Include Node Specific Variables for TPNode Proxy
     include_vars:
         dir: "{{playbook_dir}}/dataset/"
         files_matching: "tpnodes-versalex.yml"
     when: "'servers-versalex' in inventory_hostname"
     delegate_to: 127.0.0.1
     ignore_errors: yes

   - name: Setup Testprofiles in Server Side Nodes
     include_tasks: setup_flow.yml
     with_dict: "{{ versalex | default({}) }}"
     when: "'servers-versalex-1' in inventory_hostname"
     loop_control:
        loop_var: group_item     

   - name: Printing for Debug
     debug: msg="Done with Server Side DataSet Configs "
  
- rescue:
   - fail: msg="Setup Test Profile Module Failed"     