---
    - name: "Pull Docker Image from Docker Hub"
      docker_image:
        name: "{{integrations.version}}"
      register: docker_image_details
      until: docker_image_details|success
      retries: 3
      delay: 10        
        
    - name: "Run Docker Container for the image"     
      docker_container:
        name: "{{integrations.name}}"
        image: "{{integrations.version}}"
        state: started
        pull: true
        env: "{{integrations.app_args}}"
           # MYSQL_ROOT_PASSWORD: "testdocker"        
        exposed_ports: "{{integrations.port}}"        
        network_mode: bridge
        published_ports: "{{integrations.app_port}}"        
        recreate: true
        restart_policy: always
        # command: 'mysql -u root -ptestdocker -D mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;" '
      register: docker_details
      # recreate: yes
      until: docker_details|success
      retries: 3
      delay: 10
      
    - name: Docker Container IP address
      debug: msg="IP Address is:{{docker_details.ansible_facts.docker_container['NetworkSettings']['IPAddress']}}"
      
    - name: Add Container name
      add_host: 
        name: "{{integrations.name}}"
        ansible_connection: docker
        ansible_user: root
        
    # - mysql_user:
        # name: root
        # append_privs: true
        # priv: '*.*:ALL'
        # state: present

      # with_items: "{{docker_details}}"
    # tasks file for docker.install.debian.ubuntu linux
#    - debug: msg="Docker Image image_args-{{image_args}} Version-{{version}} appl_port-{{appl_port}}"
