---
# tasks file for versalex.apps
 - block:
   - name: Setting Dictionary Name for Integrations Inside
     set_fact:
        integrations: "{{group_item.value}}"
  
   # - name: Install CentOS Related Dependencies 
     # include_tasks: centos.yml
     # when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'     

   # - name: Install Docker CentOS 
     # include_tasks: "docker.install.centos.yml"
     # when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'     

   - name: Install Docker CentOS/RedHat
     include_tasks: "{{ansible_distribution | lower}}.yml"
     ignore_errors: yes
     
   - name: Install Debian Related Dependencies
     include_tasks: debian.yml
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'     
      
   - name: "Install Dockerized Install"    
     include_tasks: "docker.image.install.yml"
     register: install_status
     retries: 3
     delay: 5  
     until: install_status|success
     
   rescue:
   - fail: msg="Install Apps failed Non Docker"
     when: item.failed==true
     with_items: "{{ install_status.results }}"   
     