---
# tasks file for setup.sync
   - name: Setting Dictionary Name for Proxy Inside
     set_fact:
        versalex: "{{group_item.value}}"

   - name: Copy SetupOptions Jar File to remote location
     copy: src="{{playbook_dir}}/lib/SetupSync.jar" dest="{{versalex.install_location}}/SetupSync.jar"
        
   - name: Setup Sync in Master Versalex
     shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupSync "{{versalex.install_location}}" "{{hostvars[item]['serialno']}}" "{{hostvars[item]['ansible_eth0']['ipv4']['address']}}" "{{versalex.port}}"
     environment:
       CLASSPATH: ":{{versalex.install_location}}SetupSync.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
     args:
       executable: /bin/sh
       chdir: "{{versalex.install_location}}"
     when:  play_hosts.index(item) > 0
     with_items: "{{groups['versalex']}}"     
     register: profile_config
     ignore_errors: true