---
# tasks file for create.topology
   - name: Generate and upload sshkeys to digitalocean
     include: "upload_sshkey.yml"
     when: "'create' in control_flag"
        
   - name: Create Droplets with user passed strings
     include: create_droplet.yml mac_type="{{mach_type}}" swtype="{{group_item.key}}"
     with_items: "{{group_item.value | default([])}}"
     loop_control:
        loop_var: outer_item
     when: "'create' in control_flag"
 
   - name: Destroy Droplets with user passed strings
     include: destroy_droplet.yml mac_type="{{mach_type}}" swtype="{{group_item.key}}"
     with_items: "{{group_item.value | default([])}}"
     loop_control:
        loop_var: outer_item
     when: "'destroy' in control_flag"