---
# tasks file for create.droplet
    # - set_fact:
        # outer_item: "{{item}}"
    # - name: Print SSH Key IDouter_item.1.hardware[0].qty
      # debug: msg="SSH Key {{systestres.ssh_key}} SSH Key Id{{systestres.ssh_key.id}} doToken{{do_token}}"
    - name: Print Create Droplet Vars with Stride
      debug: msg="test check type:{{mac_type}}-{{swtype}} ramsize:{{outer_item.ram_size}} image name:{{outer_item.image_name}} Sequence Item {{item}}"
      with_sequence: start=1 end="{{outer_item.qty}}" stride=1
       #debug: msg="Type {{type}} Name {{name}} Box No{{item}}"
    - name: Ensure Public/Private Key Pair Generated in Local System and Copied to SSH dir
      user: >
       name=root
       generate_ssh_key=yes
       ssh_key_file=.ssh/id_rsa

    - name: Upload and Ensure SSH Key Exists in Digital Ocean account, Retries 3 times with delay of 5 seconds, if failure
      digital_ocean: >
       state=present
       command=ssh
       name=muthutest
       ssh_pub_key={{ lookup('file','~/.ssh/id_rsa.pub')}}
       api_token={{do_token}}            
      register: systestres
      retries: 3
      delay: 20
      until: systestres|success
     
    - name: Create  Droplet and Ensure it exists,Retries 3 times with delay of 5 seconds, if failure
      digital_ocean: 
         state: present
         command: droplet
         name: "{{mac_type}}-{{swtype}}-{{item}}"
         unique_name: yes
         size_id: "{{outer_item.ram_size}}"
         region_id: "{{outer_item.region}}"
         image_id: "{{outer_item.image_name}}"
         ssh_key_ids: "{{systestres.ssh_key.id}}"
         api_token: "{{do_token}}"
      with_sequence: start=1 end="{{outer_item.qty}}" stride=1       
      register: droplet_details
      retries: 3
      delay: 5  
      until: droplet_details|success
      
    - name: Printing IP Address of Machine
      debug: msg="Dropltet  IP address is::{{item.droplet.ip_address}}"
      with_items: "{{droplet_details.results}}"
    # - name: Add Host to Known Hosts file in LocalHost
      # known_hosts: name="{{item.droplet.ip_address}}" key="{{item.droplet.ip_address}} {{systestres.ssh_key.public_key}}"
      # with_items: "{{droplet_details.results}}"
    # - name: "Add IP's of Machines Created in Digital Ocean to Groups of Groups"
      # add_host: name="{{outer_item.0.type}}-{{outer_item.1.set}}"  groups="{{outer_item.0.type}}:children" ansible_ssh_private_key_file='/root/.ssh/id_rsa' ansible_ssh_common_args='-o PubkeyAuthentication=yes' ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null'
      # with_items: "{{droplet_details.results}}"
      
    - name: "Add IP's of Machines Created in Digital Ocean to Groups"
      add_host: 
        name: "{{item.droplet.name}} ansible_ssh_host={{item.droplet.ip_address}}  appl={{outer_item.name}} subtype={{swtype}}"
        hostname: "{{item.droplet.name}}"
        type: "{{mac_type}}"       
        ansible_host: "{{item.droplet.ip_address}}"
        groups: "{{mac_type}}-{{swtype}}"
        ansible_ssh_private_key_file: '/root/.ssh/id_rsa'
        ansible_ssh_common_args: '-o PubkeyAuthentication=yes'
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
      with_items: "{{droplet_details.results}}"
      
    - name: "Add IPs of Machines Created in Digital Ocean to Groups at Type Level"
      add_host:
        name: "{{item.droplet.name}} ansible_ssh_host={{item.droplet.ip_address}} appl={{outer_item.name}} subtype={{swtype}}"
        hostname: "{{item.droplet.name}}"
        type: "{{mac_type}}"        
        ansible_host: "{{item.droplet.ip_address}}"
        groups: "{{mac_type}}"
        ansible_ssh_private_key_file: '/root/.ssh/id_rsa'
        ansible_ssh_common_args: '-o PubkeyAuthentication=yes'
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
      with_items: "{{droplet_details.results}}"

    - name: "Add IP's of Machines Created in Digital Ocean to Groups Srvers"
      add_host: 
        name: "{{item.droplet.name}} ansible_ssh_host={{item.droplet.ip_address}}  appl={{outer_item.name}} subtype={{swtype}}"
        hostname: "{{item.droplet.name}}"
        type: "{{mac_type}}"       
        ansible_host: "{{item.droplet.ip_address}}"
        groups: "{{swtype}}"
        ansible_ssh_private_key_file: '/root/.ssh/id_rsa'
        ansible_ssh_common_args: '-o PubkeyAuthentication=yes'
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
      with_items: "{{droplet_details.results}}"
    
    - name: Wait for SSH to come up
      wait_for: host="{{item.droplet.ip_address}}" port=22 delay=5 timeout=320 state=started
      with_items: "{{droplet_details.results}}"
      #ansible_ssh_private_key_file='/root/.ssh/id_rsa' ansible_ssh_common_args ='-o PubkeyAuthentication=yes'