---
# defaults file for jmeter
jmeter_version: 3.3
jmeter_get_utl: "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-{{jmeter_version}}.tgz"
jmeter_dir: "/root/jmeter/"
fileSizes: "1000000 1500000 500000"
jmeter_plugins_tst_url: "https://jmeter-plugins.org/files/packages/jpgc-tst-2.1.zip"
jmeter_plugins_paramctrller_url: "https://jmeter-plugins.org/files/packages/jpgc-prmctl-0.3.zip"
files_per_hour: "{{files_per_hr}}"
server_datasets:
    as2:
        threads: 10
        destPath: "/root/share/as2/outboxes/"
        fileSize: "1000000 1500000 500000"
        filespermin: "{{0 if as2_filespermin == '' else  as2_filespermin}}"
        totalmins: "{{0 if as2_totalmins == '' else as2_totalmins }}"
        totalhosts: "{{0 if as2_totalhosts == '' else as2_totalhosts}}"
        totalTPNodes: "{{groups['tpnodes-versalex'] | length}}"       
tp_datasets:
    as2:
        threads: 10
        destPath: "/root/share/as2/outboxes/"
        fileSize: "1000000 1500000 500000"
        filespermin: "{{0 if as2_filespermin == '' else as2_filespermin }}"
        totalmins: "{{0 if as2_totalmins =='' else as2_totalmins }}"
        totalhosts: "{{0 if as2_totalhosts == '' else as2_totalhosts}}"
        totalTPNodes: "{{groups['tpnodes-versalex'] | length}}"       
    ftp:
        threads: 10
        destPath: "/root/share/ftp/outboxes/"        
        fileSize: "1000000 1500000 500000"
        filespermin: "{{0 if ftp_filespermin == '' else ftp_filespermin }}"
        totalmins: "{{0 if ftp_totalmins == '' else ftp_totalmins }}"
        totalhosts: "{{0 if ftp_totalhosts == '' else ftp_totalhosts}}"
        totalTPNodes: "{{groups['tpnodes-versalex'] | length}}"       
    sshftp:
        threads: 10
        destPath: "/root/share/sshftp/outboxes/"        
        fileSize: "1000000 1500000 500000"
        filespermin: "{{0 if sshftp_filespermin == '' else sshftp_filespermin }}"
        totalmins: "{{0 if sshftp_totalmins == '' else sshftp_totalmins }}"
        totalhosts: "{{0 if sshftp_totalhosts == '' else sshftp_totalhosts}}"
        totalTPNodes: "{{groups['tpnodes-versalex'] | length}}"