---
# defaults file for jmeter
jmeter_version: 3.3
jmeter_get_utl: "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-{{jmeter_version}}.tgz"
jmeter_dir: "/root/jmeter/"
fileSizes: "5000 10000 20000 40000 80000 100000 200000 400000 500000 1000000"
jmeter_plugins_tst_url: "https://jmeter-plugins.org/files/packages/jpgc-tst-2.1.zip"
jmeter_plugins_paramctrller_url: "https://jmeter-plugins.org/files/packages/jpgc-prmctl-0.3.zip"
files_per_hour: "{{files_per_hr}}"
server_datasets:
    as2:
        threads: 10
        destPath: "/root/share/as2/outboxes/"
        fileSize: "5000 10000"
        filespermin: "{{as2_filespermin}}"
        totalmins: "{{as2_totalmins}}"
        totalhosts: "{{as2_totalhosts}}"
tp_datasets:
    as2:
        threads: 10
        destPath: "/root/share/as2/outboxes/"
        fileSize: "5000 10000"
        filespermin: "{{as2_filespermin}}"
        totalmins: "{{as2_totalmins}}"
        totalhosts: "{{as2_totalhosts}}" 
    ftp:
        threads: 10
        destPath: "/root/share/ftp/outboxes/"        
        fileSize: "5000 10000 20000 40000 80000 100000 200000 400000 500000 1000000"
        filespermin: "{{ftp_filespermin}}"
        totalmins: "{{ftp_totalmins}}"
        totalhosts: "{{ftp_totalhosts}}"