---
# tasks file for jmeter
- block:
    # - name: Initialize Protocols
      # set_fact:
        # protocols: []
  
    # - name: Set Protocols
      # set_fact:
        # protocols: "{{protocols}}+['{{item.key}}'] "
      # with_dict: "{{dataset}}"

    # - name: Print Hosts Per Protocol
      # debug: msg="Total Hosts AS2 {{dataset[item.0].filespermin}} TOtal Hosts FTP {{dataset[item.1].totalhosts}}"
      # with_together: "{{protocols}}"

    - name: Passed value of Load data
      debug: msg=" Load DataSet {{load_data}}"    
      
    - name: Convert Dataset Dictionary to Jmeter Arguments
      jmeter_args:
        jmx: "/root/jmeter/apache-jmeter-3.3/bin/SysTest_Linux_New.jmx"
        protocols: "{{load_data}}"
      delegate_to: 127.0.0.1
      register: jmeter_arg
      
    - name: Print jmeter arguments
      debug: msg="Jmeter arguments to Pass-{{jmeter_arg.meta}}"
      delegate_to: 127.0.0.1


- rescue:
    - fail: msg="Jmeter Role Failed"