---
# tasks file for jmeter
- block:
      
    - name: Print Protocol Values
      debug: msg="Protocol Values Issued {{protocols}}"
      
      
    - name: Install 1.8 Open JDK
      yum:
        name: "java-1.8.0-openjdk.x86_64"
        state: present
        
    - name: Create Jmeter Download Directory
      file:
        path: "{{jmeter_dir}}"
        state: directory

    - name: Install Unzip for Extracting
      yum:
        name: unzip
        state: present
        
    - name: Jmeter Download Latest Version
      get_url:
        url: "{{ jmeter_get_utl }}"
        dest: "{{ jmeter_dir }}"
      register: jmeter_dload_status
      retries: 3
      delay: 1
      until: jmeter_dload_status | success
        
    - name: Extract JMeter to Dest Dir
      unarchive:
        src: "{{ jmeter_get_utl }}"
        dest: "{{jmeter_dir}}"
        remote_src: yes    
        
    - name: Extract JMeter Standard Plugins to Dest Dir
      unarchive:
        src: "{{ item }}"
        dest: "{{jmeter_dir}}/apache-jmeter-{{jmeter_version}}/"
        remote_src: yes
      with_items:
        - "{{jmeter_plugins_tst_url}}"
        - "{{jmeter_plugins_paramctrller_url}}"

    - name: Copy TestPlan(JMX) file to Shares
      copy: src="{{playbook_dir}}/files/SysTest_Linux_New.jmx" dest="{{jmeter_dir}}apache-jmeter-{{jmeter_version}}/bin/"

    # - name: Initialize Protocols
      # set_fact:
        # protocols: []
  
    # - name: Set Protocols
      # set_fact:
        # protocols: "{{protocols}}+['{{item.key}}'] "
      # with_dict: "{{dataset}}"

    # - name: Print Hosts Per Protocol
      # debug: msg="Total Hosts AS2 {{dataset[item.0].filespermin}} TOtal Hosts FTP {{dataset[item.1].totalhosts}}"
      # with_together: "{{protocols}}"

    - name: Convert Dataset Dictionary to Jmeter Arguments
      jmeter_args:
        jmx: "/root/jmeter/apache-jmeter-3.3/bin/SysTest_Linux_New.jmx"
        protocols: "{{protocols}}"
      delegate_to: 127.0.0.1
      register: jmeter_arg
      
    - name: Print jmeter arguments
      debug: msg="Jmeter arguments to Pass-{{jmeter_arg.meta}}"
      delegate_to: 127.0.0.1
      
    - name: Run Jmeter with Configs
      # shell: jmeter -n -t "SysTest_Linux_New.jmx" -Jas2.threads="{{dataset[item.0].threadCount}}" -Jas2.loopcount="{{(dataset[item.0].filespermin|int*dataset[item.0].totalmins|int/dataset[item.0].threadcount)}}" -Jas2.fileSize="{{dataset[item.0].fileSizes}}" -Jas2.destPath="{{dataset[item.0].share_dir}}" -Jas2.filesPerMin="{{dataset[item.0].filesPerMin}}" -Jas2.totalHosts="{{dataset[item.0].totalHosts}}"
      shell: "{{jmeter_arg.meta}}"
      environment:
         PATH: "{{ ansible_env.PATH }}:{{jmeter_dir}}apache-jmeter-{{jmeter_version}}/bin/" 
      args:
         executable: /bin/sh
         chdir: "{{jmeter_dir}}apache-jmeter-{{jmeter_version}}/bin/"         
      register: jmeter_res
      ignore_errors: yes
      async: 3600
      poll: 60
      
    - name: Print Jmeter Results
      debug: msg="{{jmeter_res.stdout_lines}}"
- rescue:
    - fail: msg="Jmeter Role Failed"