---
# tasks file for jmeter
- block:

    - name: Print Protocol Values
      debug: msg="server_datasets Protocol Values Issued {{server_datasets}}"      

    - name: Print Protocol Values
      debug: msg="TP_datasets Protocol Values Issued {{tp_datasets}}"      
      
    - name: Install 1.8 Open JDK
      yum:
        name: "java-1.8.0-openjdk.x86_64"
        state: present
        
    - name: Create Jmeter Download Directory
      file:
        path: "{{jmeter_dir}}"
        state: directory

    - name: Install Unzip for Extracting
      yum:
        name: unzip
        state: present
        
    - name: Jmeter Download Latest Version
      get_url:
        url: "{{ jmeter_get_utl }}"
        dest: "{{ jmeter_dir }}"
      register: jmeter_dload_status
      retries: 3
      delay: 3
      until: jmeter_dload_status | success
        
    - name: Extract JMeter to Dest Dir
      unarchive:
        src: "{{ jmeter_get_utl }}"
        dest: "{{jmeter_dir}}"
        remote_src: yes    
        
    - name: Extract JMeter Standard Plugins to Dest Dir
      unarchive:
        src: "{{ item }}"
        dest: "{{jmeter_dir}}/apache-jmeter-{{jmeter_version}}/"
        remote_src: yes
      with_items:
        - "{{jmeter_plugins_tst_url}}"
        - "{{jmeter_plugins_paramctrller_url}}"

    - name: Copy TestPlan(JMX) file to Shares
      copy: src="{{playbook_dir}}/files/SysTest_Linux_New.jmx" dest="{{jmeter_dir}}apache-jmeter-{{jmeter_version}}/bin/"

    - name: Set  Total Secs to Run Jmeter Scripts for Server
      set_fact:
        totalseconds: "{{(as2_totalmins|int+3)*60}}"
      when: "'servers-shares' in inventory_hostname"
      

    - name: Running Servers Side Jmeter Tests 
      include_tasks: "jmeter_tests.yml"
      vars:
        load_data: "{{server_datasets}}"
      register: srvr_tests
      when: "'servers-shares' in inventory_hostname"

    - name: Set Total Secs to Run Jmeter Scripts for Client
      set_fact:
        totalseconds: "{{(as2_totalmins|int+ftp_totalmins|int+3)*60}}"
      when: "'tpnodes-shares' in inventory_hostname"
  
    - name: Debug Server & TP Total Secs
      debug: msg="Print Total Seconds {{(totalseconds|int)}}"
  
    - name: Running TP Node Side Jmeter Tests 
      include_tasks: "jmeter_tests.yml"
      vars:
        load_data: "{{tp_datasets}}"
      when: "'tpnodes-shares' in inventory_hostname"
     
    - name: Debug Jmeter Sserver and TP Side Args
      debug: msg="Jmeter res {{jmeter_arg.meta}}"

    - name: Run Jmeter with Configs
      # shell: jmeter -n -t "SysTest_Linux_New.jmx" -Jas2.threads="{{dataset[item.0].threadCount}}" -Jas2.loopcount="{{(dataset[item.0].filespermin|int*dataset[item.0].totalmins|int/dataset[item.0].threadcount)}}" -Jas2.fileSize="{{dataset[item.0].fileSizes}}" -Jas2.destPath="{{dataset[item.0].share_dir}}" -Jas2.filesPerMin="{{dataset[item.0].filesPerMin}}" -Jas2.totalHosts="{{dataset[item.0].totalHosts}}"
      shell: "{{jmeter_arg.meta}}"
      environment:
         PATH: "{{ ansible_env.PATH }}:{{jmeter_dir}}apache-jmeter-{{jmeter_version}}/bin/" 
      args:
         executable: /bin/sh
         chdir: "{{jmeter_dir}}apache-jmeter-{{jmeter_version}}/bin/"         
      register: jmeter_res
      async: "{{totalseconds|int}}"
      poll: 60
      ignore_errors: yes
      
    - name: Print Jmeter Results
      debug: msg="{{jmeter_res.stdout_lines}}"
      
- rescue:
    - fail: msg="Jmeter Role Failed"