---
# tasks file for download.product
- block:     
    - name: Setup License for Versalex
      include: "setup_vexlicense.yml"
      with_dict: "{{ versalex | default({}) }}"
      loop_control:
         loop_var: lic_group 
  rescue:
      - fail: msg="Setting License Failed"