---
 dockerize: "false"
 application: mysql
 use_dockerfile: "false"
# application_docker_image: "mysql:latest"
# application_args: "MYSQL_ROOT_PASSWORD=testdocker"
 app_dockersrc_dir: "/home/SystemTest/"
 app_dockerdest_dir: "/root/"
 app_docker_image_name: testdockerfile
 app_docker_image_tag: latest
 versalex_find_version_url: http://contd.cleo.com/nexus/service/local/artifact/maven/resolve
 versalex_download_version_url: http://contd.cleo.com/nexus/service/local/artifact/maven/content
 nexus_repoid: releases
 versalex_groupid: com.cleo.installers
 versalex_artifactid: Harmony
 versalex_classifier: linux64-jre18
 versalex_packaging: bin
 versalex_version: 5.3.0.0
 find_rest_url: "{{versalex_find_version_url}}?r={{nexus_repoid}}&g={{versalex_groupid}}&a={{versalex_artifactid}}&c={{versalex_classifier}}&p={{versalex_packaging}}&v={{versalex_version}}"
 download_rest_url: "{{versalex_download_version_url}}?r={{nexus_repoid}}&g={{versalex_groupid}}&a={{versalex_artifactid}}&c={{versalex_classifier}}&p={{versalex_packaging}}&v={{versalex_version}}"
 download_location: "/home/SystemTest/vexdownload/"
 install_location: "/root/Harmony/"
 license_file_path: "/home/SystemTest/license_key.txt"
 
 licenser_nexus_repourl: http://contd.cleo.com/nexus/service/local/artifact/maven/content
 licenser_repoid: cleo
 licenser_groupid: com.cleo.util
 licenser_artifactid: LexiComLicenser_2
 licenser_version: LATEST
 download_licgenerator_url: "{{licenser_nexus_repourl}}?r={{licenser_repoid}}&g={{licenser_groupid}}&a={{licenser_artifactid}}&e=jar&v={{licenser_version}}"