---
 # - name: Setting Dictionary Name for Proxy Inside
   # set_fact:
      # versalex: "{{conf_tp.value}}"
 
 - name: Set Dataset Key 
   set_fact:
        dset_key: "{{conf_dataset.key}}"
        
 - name: Copy SetupOptions Jar File to remote location
   copy: src="{{playbook_dir}}/library/" dest="{{versalex.install_location}}lib/"

 - name: Create Import Location Directory, if not Exists
   file: path="{{versalex.install_location}}systestcerts" state=directory
   # when: node_type == 'Receiver'
 - name: Copy All Certs from Local to Remote Import Location
   synchronize: src="{{playbook_dir}}/files/systestcerts/" dest="{{versalex.install_location}}systestcerts/"   
   # when: setup_profiles.vex_product is defined and setup_profiles.vex_product != 'VLProxy' and setup_profiles.node_type == 'Receiver'   
 - name: Set macro name to Empty if  not defined
   set_fact: 
        macro_name: ""
   when: shares is not defined
   
 - name: Set macro name if defined
   set_fact: 
        macro_name: "%datashare%"
   when: shares is defined
      
 - name: "Configure Test Profiles in Remote Machines for Receiver/TP Side-Server"
   shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupTestProfile "{{versalex.name}}" "{{versalex.install_location}}" "{{item.name}}" "{{item.hr}}" "{{item.mailbox_range}}" "{{item.action_range}}" "{{item.ip}}" "80"  "{{macro_name}}" "{{item.host_custom_props}}" "{{item.mailbox_custom_props}}" "{{item.action_custom_props}}" "false"
   environment:
     CLASSPATH: ":{{versalex.install_location}}SetupTestProfile.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
   args:
     executable: /bin/sh
     chdir: "{{versalex.install_location}}"
   with_items: "{{ dataset[dset_key]  }}"
   when: item.name | lower == 'as2'
   register: profile_config

 - name: "Configure Test Profiles in Remote Machines for Receiver/TP Side -Client"
   shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupTestProfile "{{versalex.name}}" "{{versalex.install_location}}" "{{item.name}}" "{{item.hr}}" "{{item.mailbox_range}}" "{{item.action_range}}" "{{item.ip}}" "9021"  "{{macro_name}}" "{{item.host_custom_props}}" "{{item.mailbox_custom_props}}" "{{item.action_custom_props}}" "false"
   environment:
     CLASSPATH: ":{{versalex.install_location}}SetupTestProfile.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
   args:
     executable: /bin/sh
     chdir: "{{versalex.install_location}}"
   with_items: "{{ dataset[dset_key]  }}"
   when: item.name | lower == 'ftp'
   register: profile_config

   
   # when: setup_profiles.vex_product is defined and setup_profiles.vex_product != 'VLProxy' and setup_profiles.node_type == 'Receiver'