     - name: Configure Schedule Actions on Sender and Receiver Side Nodes
       shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupTestProfile "{{vex_product}}" "{{install_location}}" "{{schedule_actions}}"
       environment:
         CLASSPATH: ":{{install_location}}SetupTestProfile.jar:{{install_location}}lib/*:{{install_location}}lib/help/*:{{install_location}}lib/hibernate/*:{{install_location}}lib/secureshare/*:{{install_location}}webserver/AjaxSwing/lib/*:{{install_location}}lib/json/*"
       args:
         executable: /bin/sh
         chdir: "{{install_location}}"
       register: profile_config
       when: vex_product is defined and vex_product != 'VLProxy'

     - name: Kill Harmony Processes Karaf and OSGI
       shell: "kill -9 $(ps -aef |grep 'karaf.main' |grep -v grep |awk '{print $2 \"\t\" $3}')"
       register: kill_status
       # when: vex_product is defined and vex_product != 'VLProxy' 
       
     - name: Print Kill Details
       debug: msg="Kll Details:{{kill_status}}"
       when: vex_product is defined and vex_product != 'VLProxy'
       
     - name: Remove schedule Lock File if exists
       file:
        path: "{{install_location}}schedule.lck"
        state: absent
       # when: vex_product is defined and vex_product != 'VLProxy'
       
     - name: Wait for port 5080 to get Stopped
       wait_for: host="{{inventory_hostname}}" port="{{vex_port}}" delay=20 state=stopped
       # when: vex_product is defined and vex_product != 'VLProxy'
       
     - name: Start VersalEx Product Daemon   
       shell: "{{item}}"
       args:
         chdir: "{{install_location}}"
       with_items:
         - ./{{vex_product}}d start
       register: startvexstatus
       
     - name: Print Start Results Status
       debug: msg="Start Status Results{{startvexstatus}}"
       when: vex_product is defined and vex_product != 'VLProxy'
       
     - name: Wait for versalex to get Started
       wait_for: host="{{inventory_hostname}}" port="{{vex_port}}" delay=30 state=started
       # when: vex_product is defined and vex_product != 'VLProxy'