---
# tasks file for setup.testprofiles
- block:
   - name: Setting Dictionary Name for Proxy Inside
     set_fact:
        versalex: "{{group_item.value}}"

   - name: Configure {{inc_file}} Side Nodes
     include: "{{inc_file}}.yml"
     with_dict: "{{ dataset | default({}) }}"
     # when: "'servers-versalex' in inventory_hostname"
     loop_control:
        loop_var: conf_dataset  

   - name: Print Debug Msgs Setup Flow
     debug: msg="Done with Config"   
   # - name: Configure TP Side Nodes
     # include: configure_tp.yml
     # static: no
     # when: vex_product is defined and not include_vars_status | failed and vex_product != 'VLProxy' and node_type == 'Receiver'
   # - name: Configure Post Setup Configs
     # include: post_setup.yml
     # when: vex_product is defined and vex_product != 'VLProxy'
- rescue:
   - fail: msg="Setup Test Profile Module Failed" 

   
   
   
   # - name: Setting TpHost Count
     # set_fact:        
       # tp_count: "{{ groups['tpnodes-versalex'] | length | int}}"

   # - name: Install RSYNC packages
     # yum: name=rsync state=present
     # when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
   # # - name: Call PreSetup Tasks
     # # include: pre_setup.yml
     # # when: "'servers-versalex' in inventory_hostname"

   # - name: Creates Map Directory
     # file:
       # path: "{{role_path}}/res/"
       # state: directory
       # mode: 0777
     # delegate_to: 127.0.0.1
          
   # - name: TestProfile map
     # template: src=setup_testprofile.j2 dest="{{role_path}}/res/{{inventory_hostname}}-map.yml"
     # # when: "'servers-versalex' in inventory_hostname"
     # delegate_to: 127.0.0.1

     
   # - name: Include Node Specific Variables
     # include_vars: "{{role_path}}/res/{{inventory_hostname}}-map.yml"
     # # when: "'servers-versalex' in inventory_hostname"
     # delegate_to: 127.0.0.1
     # ignore_errors: yes   