dependencies:
        - { role: 'configure.product/common/use_systestjar' }
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
   # - { role: setup.testprofiles/pre_setup, when: "'servers-versalex' in inventory_hostname" }
