---
# tasks file for dockerized.install
   # - set_fact:
       # install_item: "{{item}}"
   # - set_fact: { "{{item.key}}": "{{item.value}}" }     
     # with_dict: "{{install_item.value}}"
   # - set_fact:
       # { db_type: "{{db.name}}" }
   # - debug: msg="DB TYPE {{db_type}}"   
   - debug: msg="Docker Image name-{{db.name}} Version-{{db.version}}    use_docker_image docker {{db.use_docker_image}}"
#   - set_fact:
#       install_item: "{{item}}"
       #ignore_erros: true
       
#   - set_fact:
#       image: "{{install_item[1].app_name}}:{{install_item[1].app_version}}"
#       exp_port: "{{install_item[1].app_port}}"       
#       use_docker_image: "{{install_item[1].use_docker_image}}"
       #app_srcdir: "{{install_item[1].app_srcdir}}"        
       #app_destdir: "{{install_item[1].app_destdir}}" 
       #app_image_name: "{{install_item[1].app_image_name}}" 
       #app_image_tag: "{{install_item[1].app_image_tag}}"
       
