---
# tasks file for setup.AS2
- block:
    - name: Setup AS2 Profiles using Rest with Proxy
      setup_as2:
        host_name: "{{hostname}}"
        server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        proxy_hosts: "{{ groups['servers-proxy'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        tp_hosts: "{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        dataset: "{{dataset}}"
      register: rest_status      
      delegate_to: 127.0.0.1
- rescue:
   - fail: msg="Setup Test Profile Module Failed"     