---
# tasks file for setup.testprofiles
- block:
   - name: Setup Testprofiles in Server Side Nodes for SSHFTP
     include_tasks: configure_server.yml
     with_dict: "{{ versalex | default({}) }}"
     when: "'servers-versalex-1' in inventory_hostname"
     loop_control:
        loop_var: group_item
     

   - name: Printing for Debug
     debug: msg="Done with Server Side DataSet Configs "
  
- rescue:
   - fail: msg="Setup Test Profile Module Failed"     