---
    # - name: Print Create Droplet Vars with Stride
      # debug: msg="test check type:{{mac_type}}-{{swtype}} ramsize:{{outer_item.ram_size}} image name:{{outer_item.image_name}} Sequence Item {{item}}"
      # with_sequence: start=1 end="{{outer_item.qty}}" stride=1

    - name: Install Pip Dopy
      pip: >
       name=dopy
      
    # - name: Ensure Public/Private Key Pair Generated in Local System and Copied to SSH dir
      # user: >
       # name=root
       # generate_ssh_key=yes
       # ssh_key_file=.ssh/id_rsa

    - name: Upload and Ensure SSH Key Exists in Digital Ocean account, Retries 3 times with delay of 5 seconds, if failure
      digital_ocean: >
       state=present
       command=ssh
       name=st-versalex
       ssh_pub_key='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwu+OSlLejtrz6HlnAH/JNoLRdoRy0Aw6e1IrBrJ3MEy1onNu89fhdD7Kv0OSWOwbTY4tEls10+76SImLJj0DJDqMlZRWYzUzlFXIC9oRgkTK4p7V0DtM5yVoh3AK6Ts8zYAiVke/FT7BGPi76AaiASys9fMo3YeV91lv8iyiDSSUphOom+EINtFQtv6nH5bWTXmsvyYXiKV0XaHMyT9+Pr+t0cci4Rmw7/hRvYcrE0Tr06KOAn9SJZuKsMaOTxhX98bqiL+p7pHKWWvlO3vB78DdeIq45s5rLSyJQrh2yPc79sbPWUiZt6mIFESlb/I2Zs8xjgbafjG338qRIMGw1 ansible-generated on 743a82357330'
       api_token={{do_token}}            
      register: uploadstatus
      retries: 3
      delay: 20
      until: uploadstatus|success
      
    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"      
   
    - name: Print SSH File
      shell: cat ~/.ssh/id_rsa.pub 
      register: kn_hst
  
    - name: Print known hosts
      debug: msg="Knwn Hosts {{kn_hst}}"
      
    - service:
        name: sshd
        state: restarted

   