---
    - name: Preparing for Instance Creations on EC2
      debug: msg="EC2 Details --{{mac_type}}-{{swtype}}"
      delegate_to: 127.0.0.1
      
    - name: Create EC2 Instance on AWS
      ec2:
         group: "{{outer_item.security_group}}"
         key_name: "{{outer_item.key_pair}}"
         # aws_access_key: "{{aws_access_key}}"
         # aws_secret_key: "{{aws_secret_access_key}}"
         instance_type: "{{outer_item.instance_type}}"         
         image: "{{outer_item.image}}"
         wait: true
         region: "{{outer_item.region}}"
         count: 1
         assign_public_ip: yes
         vpc_subnet_id: "{{outer_item.vpc_subnet_id}}"
         instance_tags:
            Name: "{{mac_type}}-{{swtype}}-{{item}}"
            type: "{{mac_type}}-{{username}}"
      with_sequence: start=1 end="{{outer_item.qty}}" stride=1       
      register: ec2_status

    - name: Print  ec2 details
      debug: msg="EC2 Details PART 1--{{ec2_status.results}}"
      delegate_to: 127.0.0.1
      
    - name: Print aws ec2 details
      debug: msg="EC2 Details --{{item.1.public_ip}}"
      with_subelements:
            - "{{ec2_status.results}}"
            - instances
      delegate_to: 127.0.0.1
    
    - name: "Add IP's of Machines Created in AWS to Groups"
      add_host: 
        name: "{{item.1.tags.Name}} ansible_ssh_host={{item.1.public_ip}} ansible_user=ec2-user ansible_become=true appl={{outer_item.name}} subtype={{swtype}}"
        hostname: "{{item.1.tags.Name}}"
        type: "{{mac_type}}"
        ansible_host: "{{item.1.public_ip}}"       
        groups: "{{mac_type}}-{{swtype}},{{mac_type}},{{swtype}}"
      with_subelements:
            - "{{ec2_status.results}}"
            - instances
      register: ec2_groups
      no_log: true      
      delegate_to: 127.0.0.1

    - name: Print IP in the Groups Memory 
      debug: msg="Group in the Memory {{ item}}"
      with_items: "{{groups}}"
      delegate_to: 127.0.0.1
      
    - name: Wait for SSH to come up
      wait_for: host="{{item.1.public_ip}}" port=22 delay=60 timeout=320 state=started
      with_subelements:
            - "{{ec2_status.results}}"
            - instances
      delegate_to: 127.0.0.1
      no_log: true