---
machine_type: digitalocean
do_token: "{{do_api_token}}"
systestnodes:
       - type: servers
         configs:
          - set: versalex
            hardware:
                - name: Harmony
                  ram_size: 1gb
                  region: nyc1
                  image_name: "centos-6-x64"
                  qty: 1
            application:
                - name: Harmony
                  version: 5.3.0-SNAPSHOT
                  install_location: "/root/Harmony/"
                  vex_jmx_port: 3022
          - set: db
            hardware:
                - name: mysql
                  ram_size: 4gb
                  region: nyc1
                  image_name: "centos-6-x64"
                  qty: 1                      
            application:
                - name: mysql
                  version: "mysql:latest"
          - set: proxy
            hardware:
                - name: VLProxy
                  ram_size: 1gb
                  region: nyc1
                  image_name: "centos-6-x64"
                  qty: 1                 
            application:
                - name: VLProxy
                  version: 5.3.0-SNAPSHOT
                  install_location: "/root/VLProxy/"                  
       - type: tpnodes
         configs:
          - set: versalex
            hardware:
                - name: Harmony
                  ram_size: 1gb
                  region: nyc1
                  image_name: "centos-6-x64"
                  qty: 1                 
            application:
                - name: Harmony
                  version: 5.3.0-SNAPSHOT
                  install_location: "/root/TPHarmony/"