---
- hosts: "{{machine_type}}"
  roles:
     - { role: configure.product/vlproxy,email_on_fail_addr: 'muthukumarc@cleo.com' }
     - { role: configure.product, machine_type: "{{machine_type}}" }

- hosts: shares
  roles:
    - { role: configure.product/common}
    - { role: configure.product/server_share }
    
- hosts: versalex
  roles: 
    - { role: configure.product/common}
    - { role: configure.product/client_share }      