---
- hosts: "{{machine_type}}"
  roles:
    - { role: configure.product/common}

- hosts: shares
  tasks:
    - name: Configure Server Side Shares
      include_role:
        name: configure.product/server_share
      with_dict: "{{ shares | default({}) }}"
      loop_control:
          loop_var: srvr_share
          
- hosts: "{{machine_type}}"
  roles:
    - { role: configure.product/client_share, when: shares is defined}

- hosts: "{{machine_type}}"
  roles:
    - { role: configure.product }
