---
- hosts: "versalex:proxy:shares"
  roles:
    - { role: configure.product/common}
    
- hosts: "versalex"
  roles:
    - { role: 'configure.product/common/use_systestjar',tags: ['use_systestjar'] }

- hosts: shares
  tasks:
    - name: Configure Server Side Shares
      include_role:
          name: configure.product/server_share
      with_dict: "{{ shares | default({}) }}"
      loop_control:
          loop_var: srvr_share
      tags:
        - 'server_share'
        
- hosts: versalex
  tasks:
    - name: Configure Client Side Shares
      include_role:
        name: configure.product/client_share
      with_dict: "{{ versalex | default({}) }}"
      loop_control:
          loop_var: clishare
      tags:
        - 'client_share'

          
- hosts: "versalex"
  roles:
    - { role: configure.product/mem,tags: ['mem'] }    

- hosts: "proxy"
  # connection: local
  roles:
    - { role: configure.product/vlproxy,external_address: "{{ansible_ssh_host}}" ,email_on_fail_addr: 'muthukumarc@cleo.com',tags: ['setup_vlproxy'] }
    
- hosts: "versalex:integrations"
  roles:
    - { role: configure.product/db,when: integrations is defined,tags: ['db'] } 

- hosts: "versalex:proxy"
  roles:
    - { role: configure.product/proxy,when: proxy is defined,tags: ['vex_proxy'] } 

- hosts: "versalex:integrations"
  roles:
    - { role: configure.product/ldap,when: ldap is defined,tags: ['ldap'] } 
        
- hosts: versalex
  # strategy: free
  roles:
    - { role: common/versalex/restart/,tags: ['versalex-restart'] }     
        
- hosts: "versalex:proxy"
  roles:
    - { role: configure.product/tests }
