---
- hosts: "versalex:proxy:shares"
  roles:
    - { role: configure.product/common}

- hosts: shares
  tasks:
    - name: Configure Server Side Shares
      include_role:
          name: configure.product/server_share
      with_dict: "{{ shares | default({}) }}"
      loop_control:
          loop_var: srvr_share

- hosts: versalex
  tasks:
    - name: Configure Client Side Shares
      include_role:
        name: configure.product/client_share
      with_dict: "{{ versalex | default({}) }}"
      loop_control:
          loop_var: clishare
          
- hosts: "versalex"
  roles:
    - { role: configure.product/mem }    


- hosts: "proxy"
  # connection: local
  roles:
    - { role: configure.product/vlproxy,external_address: "{{ansible_ssh_host}}" ,email_on_fail_addr: 'muthukumarc@cleo.com' }
   
    
- hosts: "versalex:integrations:proxy"
  roles:
    - { role: configure.product } 

- hosts: "versalex"
  strategy: free
  roles:
    - { role: common/versalex/restart/,tags: ['versalex-restart'] }     
        
- hosts: "versalex:proxy"
  roles:
    - { role: configure.product/tests }
