---
- hosts: "versalex:proxy"
  # pre_tasks:
    # - meta: refresh_inventory
  roles:
    - { role: install.product/common}

- hosts: "versalex"
  strategy: free
  roles:
    - { role: install.product/license }

- hosts: "versalex"
  # strategy: free
  roles:
    - { role: install.product, prod_dict: "{{ versalex }}" } 
    
- hosts: "proxy"
  # strategy: free
  roles:    
    - { role: install.product, prod_dict: "{{ proxy }}" } 

- hosts: "versalex"
  strategy: free
  roles:
    - { role: install.product/restify } 

- hosts: "versalex"
  strategy: free
  roles:
    - { role: common/versalex/start/,tags: ['versalex-start'] } 
    
- hosts: "versalex"
  strategy: free
  roles:
    - { role: install.product/tests } 
