---
- hosts: "versalex:proxy:integrations:shares"
  roles:
    - { role: common/versalex/deps }

- hosts: "versalex"
  roles:
    - { role: install.product/license }

- hosts: "versalex"
  roles:
    - { role: install.product, prod_dict: "{{ versalex }}" } 
    
- hosts: "proxy"
  roles:    
    - { role: install.product, prod_dict: "{{ proxy }}" } 

- hosts: "versalex"
  roles:
    - { role: install.product/restify } 

    
- hosts: "versalex"
  roles:
    - { role: common/versalex/start_stop/,status: start,tags: ['versalex-start_stop'] } 
    
- hosts: "versalex"
  connection: local  
  roles:
    - { role: install.product/listener/,certname: "LOC_LIST",tags: ['create_listener_cert'] }
    
- hosts: "versalex"
  roles:
    - { role: install.product/listener/update_props,certname: "LOC_LIST",tags: ['listener-props'] }
    - { role: common/versalex/restart/,tags: ['versalex-restart'] }

- hosts: "versalex"
  strategy: free
  roles:
    - { role: install.product/tests }  