---
- name: Installs Versalex Dependencies 
  hosts: "versalex:proxy:integrations:shares"
  roles:
    - { role: common/versalex/deps,tags: 'package-deps' }

- name: Generates and setups license keys for versalex instance
  hosts: "versalex"
  roles:
    - { role: install.product/license,tags: 'setup-license' }

- name: Downloads and Installs versalex product
  hosts: "versalex"
  roles:
    - { role: install.product, prod_dict: "{{ versalex }}",tags: 'install-versalex' } 

- name: Downloads and Installs VLProxy
  hosts: "proxy"
  roles:    
    - { role: install.product, prod_dict: "{{ proxy }}",tags: 'install-proxy' } 

- name: Enabled VLNavigator Users and Restifies versalex products
  hosts: "versalex"
  roles:
    - { role: install.product/restify,tags: ['enable-rest'] } 

- name: Start and stop versalex products    
  hosts: "versalex"
  roles:
    - { role: common/versalex/start_stop/,status: start,tags: ['versalex-start_stop'] } 
    
- name: Generates Signing Certificates using Python module
  hosts: "versalex"
  connection: local  
  roles:
    - { role: install.product/listener/,certname: "LOC_LIST",tags: ['setup-listener'] }

- name: Apply Listener Properties with Signing Certificates    
  hosts: "versalex"
  roles:
    - { role: install.product/listener/update_props,certname: "LOC_LIST",tags: ['setup-listener'] }
    - { role: common/versalex/restart/,tags: ['versalex-restart'],tags: ['setup-listener'] }

- name: Validates versalex instances by rest calls        
  hosts: "versalex"
  strategy: free
  roles:
    - { role: install.product/tests,tags: 'install-tests' }  