---
- name: Installs Versalex Dependencies 
  hosts: "versalex:proxy:integrations:shares"
  roles:
    - { role: common/versalex/deps,tags: 'package-deps' }

- name: Generates and setups license keys for versalex instance
  hosts: "versalex"
  roles:
    - { role: install.product/license,tags: 'setup-license' }

- name: Downloads and Installs versalex product
  hosts: "versalex"
  roles:
    - { role: install.product, prod_dict: "{{ versalex }}",tags: 'install-versalex' } 

- name: Downloads and Installs VLProxy
  hosts: "proxy"
  roles:    
    - { role: install.product, prod_dict: "{{ proxy }}",tags: 'install-proxy' } 

- name: Enabled VLNavigator Users and Restifies versalex products
  hosts: "versalex"
  roles:
    - { role: install.product/restify,tags: ['enable-rest'] } 

- name: Start and stop versalex products    
  hosts: "versalex"
  roles:
    - { role: common/versalex/start_stop/,status: start,tags: ['versalex-start_stop'] } 
    
- name: Generates Signing Certificates using Python module
  hosts: "versalex"
  connection: local  
  roles:
    - { role: install.product/listener/,protocol_name: "AS2",certname: "LOC_LISTM",tags: ['setup-listener'] }

- name: Apply Listener Properties with Signing Certificates    
  hosts: "versalex"
  roles:
    - { role: install.product/listener/update_props,certname: "LOC_LISTM",tags: ['setup-listener'] }

- name: Apply Listener Properties for FTP 
  hosts: "versalex"
  roles:
    - { role: install.product/listener/ftp,when: (dataset is defined and dataset.ftp|default('undefined') ) ,portVal: "9021", tags: ['setup-listener-ftp'] }
    
- name: Generates Signing Certificates using Python module for SSHFTP
  hosts: "versalex"
  connection: local  
  roles:
    - { role: install.product/listener/,when: (dataset is defined and dataset.sshftp|default('undefined') ),protocol_name: "SSHFTP",certname: "SSHFTP_MM",tags: ['setup-listener-sshftp'] }
    
- name: Apply Listener Properties with Signing Certificates for SSHFTP 
  hosts: "versalex"
  roles:
    - { role: install.product/listener/sshftp,when: (dataset is defined and dataset.sshftp|default('undefined') ) ,certname: "SSHFTP_MM",portVal: "9052", tags: ['setup-listener-sshftp'] }
    - { role: common/versalex/restart/,tags: ['versalex-restart'],tags: ['setup-listener-sshftp'] }
    
- name: Validates versalex instances by rest calls        
  hosts: "versalex"
  strategy: free
  roles:
    - { role: install.product/tests,tags: 'install-tests' }  