---
- hosts: "versalex"
  roles:
    - { role: configure.product/jmx,tags: ['setup-jmx'] } 

- hosts: "versalex"
  #strategy: free
  roles:
    - { role: common/versalex/restart/,tags: ['versalex-restart'] } 
    
- hosts: "versalex"
  roles:
    - { role: setup.testprofiles/tests, tags: ['rest','java'] }
      
- hosts: "versalex"
  roles:
    - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,stop' ,tags: ['rest'] }
    - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,start' ,tags: ['rest'] }

- hosts: "servers-versalex"
  roles:
    - {role: setup.sync,tags: ['setup-sync']}   
    
# - hosts: "tpnodes-versalex"
  # roles:
    # - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,start' ,tags: ['rest'] }

- hosts: "shares"
  roles: 
      - { role: run.tests/,as2_filespermin: "{{as2_filespermin|default(0)}}",as2_totalmins: "{{as2_totalmins|default(0)}}",as2_totalhosts: "{{as2_totalhosts|default(0)}}",ftp_filespermin: "{{ftp_filespermin|default(0)}}",ftp_totalmins: "{{ftp_totalmins|default(0)}}",ftp_totalhosts: "{{ftp_totalhosts|default(0)}}" }
