---
- hosts: "servers-versalex-1"
  roles:
    - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,stop' ,tags: ['rest'] }
    - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,start' ,tags: ['rest'] }

- hosts: "tpnodes-versalex"
  roles:
    - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,stop' ,tags: ['rest'] }
    - { role: setup.testprofiles/str_command/,cmdline_str: 'scheduler,start' ,tags: ['rest'] }

- hosts: "versalex"
  roles:
    - { role: configure.product/jmx } 

- hosts: "versalex"
  strategy: free
  roles:
    - { role: common/versalex/restart/,tags: ['versalex-restart'] } 
    
# - hosts: "servers-shares"
  # vars:
    # load_datasets:
            # as2:
                # filespermin: "{{as2_filespermin}}"
                # totalmins: "{{as2_totalmins}}"
                # totalhosts: "{{as2_totalhosts}}"        

  # roles:
    # - { role: run.tests/,protocols: "{{load_datasets}}" }
    
# - hosts: "tpnodes-shares"
  # vars:
    # load_datasets:
            # as2:
                # filespermin: "{{as2_filespermin}}"
                # totalmins: "{{as2_totalmins}}"
                # totalhosts: "{{as2_totalhosts}}"
            # ftp:
                # filespermin: "{{ftp_filespermin}}"
                # totalmins: "{{ftp_totalmins}}"
                # totalhosts: "{{ftp_totalhosts}}"
  # roles:
    # - { role: run.tests/,protocols: "{{load_datasets}}" } 