---
machine_type: digitalocean
do_token: 3722b41e3aab0efb96af5aa45dbd0c9a358988c8d0bde96ee46b5e82f4aecdb7
hardware:
   versalex:           
      - name: harmony
        ram_size: 1gb
        region: nyc1
        image_name: "centos-6-x64"
        qty: 1
software:
   versalex:
      - name: harmony
        version: 5.4.1-SNAPSHOT
        install_location: "/root/Harmony/"
        vex_jmx_port: 3022