---
- name: Setups sync between master and other versalex  instances of server side
  hosts: "servers-versalex"
  roles:
    - {role: setup.sync,tags: ['setup-sync','rest']}

- name: Setups as2 profiles for server and tpnodes using rest
  hosts: "versalex:proxy"
  roles:
    - { role: setup.testprofiles/common, when: "'servers-versalex' in inventory_hostname",tags: ['rest','common','java'] }
    - { role: setup.testprofiles/rest/as2/, hostname: "AS2WW",when: "'servers-versalex-1' in inventory_hostname",tags: ['rest','rest-as2'] }

- name: "Setups SSH ftp profiles for server(java) and tpnodes(rest)"
  hosts: "versalex:proxy"
  roles:
    - { role: setup.testprofiles/rest/sshftp/server/, when: "'servers-versalex' in inventory_hostname",tags: ['rest','rest-sshftp'] }
    - { role: setup.testprofiles/rest/sshftp/client/, hostname: "SSHFTP",when: "'servers-versalex-1' in inventory_hostname",tags: ['rest','rest-sshftp'] }
   
- name: "Setups ftp profiles for server(java) and tpnodes(rest)"
  hosts: "versalex:proxy"
  roles:
    - { role: setup.testprofiles/rest/ftp/server/, when: "'servers-versalex' in inventory_hostname",tags: ['rest','rest-ftp'] }
    - { role: setup.testprofiles/rest/ftp/client/, hostname: "FTPHost",when: "'servers-versalex-1' in inventory_hostname",tags: ['rest','rest-ftp'] }

- name: Schedule actions for server master node
  hosts: "servers-versalex[0]"
  roles:
    - { role: setup.testprofiles/rest/schedule_actions/, schedule_option: "on file polling continuously",action_type: "send", tags: ['schedule-actions-server','rest'] }

- name: Schedule actions for tp nodes
  hosts: "tpnodes-versalex"
  roles:
    - { role: setup.testprofiles/rest/schedule_actions/,schedule_option: "on file polling continuously",action_type: "send", tags: ['schedule-actions-tp','rest'] }    

- name: Setups server side profiles using java    
  hosts: "versalex:proxy"
  roles:    
    - { role: setup.testprofiles/setup_server, when: "'servers-versalex' in inventory_hostname",tags: ['java'] }

- name: Setups tp node side profiles using java    
  hosts: "versalex:proxy"
  roles:
     - { role: setup.testprofiles/tp_dataset, when: "'servers-versalex' in inventory_hostname",tags: ['java']  }
     - { role: setup.testprofiles/setup_tp,tags: ['java']  }
