---
- hosts: "servers:tpnodes"
  connection: local
  tasks:
    - name: Setup FTP Client Profiles using Rest
      setup_ftp_client:
        host_name: "FTPF"
        server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        proxy_hosts: "{{ groups['servers-proxy'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        tp_hosts: "{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        dataset: "{{dataset}}"
      when: "'servers-versalex-1' in inventory_hostname"
      register: rest_status      
      delegate_to: 127.0.0.1
          
    - name: Debug Rest Details
      debug: msg="Rest Details{{rest_status}}"
      delegate_to: 127.0.0.1