---
- hosts: "{{machine_type}}"
  connection: local
  tasks:
        - name: Test Host vars 
          setup_host_vars:
            usr_src: "{{playbook_dir}}/files/servers.yml"
            hostvars_dest: "{{playbook_dir}}/host_vars/{{inventory_hostname}}.yml"
          register: host_vars
         
        - name: Print Host Vars Message
          debug: var=host_vars
          
- hosts: localhost
  connection: local
  tasks:          
        - name: Test group vars 
          setup_group_vars:
            usr_src: "{{playbook_dir}}/files/servers.yml"
            default_src: "{{playbook_dir}}/files/defaults.yml"
          register: group_vars
         
        - name: Print Group Vars Message
          debug: var=group_vars
     
  # vars_files:      
     # - "{{machine_type}}.yml"
     # # - "vars/defaults.yml"
  # roles:    
     # - { role: "setup.group.vars" }
     
# - hosts: "{{machine_type}}"
  # connection: local
  # vars_files:      
     # - "{{machine_type}}.yml"
  # roles:    
     # - { role: "setup.host.vars" }