---
- name: Validate hosts file for {{machine_type}}
  hosts: localhost
  connection: local
  vars_files:
    - "{{playbook_dir}}/files/{{cloud_provider}}/{{machine_type}}.yml"
  roles:   
    - {role: setup.topology/digitalocean/tests }  
      
- name: "Setup host_vars files"
  hosts: "{{machine_type}}"
  connection: local
  tasks:   
    - name: Create Inventory Dir
      file: 
        path: "{{playbook_dir}}/inventories/{{cloud_provider}}/{{machine_type}}/host_vars/"
        state: directory
        recurse: yes
      delegate_to: 127.0.0.1
      
    - name: "Create Servers and TPNodes Under Host Vars using Templates "
      template: src="{{playbook_dir}}/files/{{cloud_provider}}/{{item}}.j2" dest="{{playbook_dir}}/files/{{cloud_provider}}/{{item}}"
      with_items: 
            - "servers.yml"
            - "tpnodes.yml"      
        
    - name: Create Host Vars
      setup_host_vars:
        usr_src: "{{playbook_dir}}/files/{{cloud_provider}}/{{machine_type}}.yml"
        hostvars_dest: "{{playbook_dir}}/inventories/{{cloud_provider}}/{{machine_type}}/host_vars/{{inventory_hostname}}.yml"
      register: host_vars

- name: "Setup group_vars files"
  hosts: localhost
  connection: local
  tasks:
    - name: Create group_vars Dir
      file: 
        path: "{{playbook_dir}}/inventories/{{cloud_provider}}/{{machine_type}}/group_vars/"
        state: directory

    - name: "Create {{machine_type}} Dir"
      file: 
        path: "{{playbook_dir}}/inventories/{{cloud_provider}}/{{machine_type}}/group_vars/"
        state: directory
        
    - name: Create Group Vars 
      setup_group_vars:
        mach_type: "{{machine_type}}"
        cloud_provider: "{{cloud_provider}}"
        usr_src: "{{playbook_dir}}/files/{{cloud_provider}}/{{machine_type}}.yml"
        default_src: "{{playbook_dir}}/files/defaults.yml"
      register: group_vars
     
    - name: Print Group Vars Message
      debug: var=group_vars
