---
- hosts: "{{machine_type}}"
  connection: local
  tasks:   
    - name: Create Inventory Dir
      file: 
        path: "{{playbook_dir}}/inventories/{{machine_type}}/host_vars/"
        state: directory
        recurse: yes
      delegate_to: 127.0.0.1
        
    - name: Create Host Vars
      setup_host_vars:
        usr_src: "{{playbook_dir}}/files/{{machine_type}}.yml"
        hostvars_dest: "{{playbook_dir}}/inventories/{{machine_type}}/host_vars/{{inventory_hostname}}.yml"
      register: host_vars
      
- hosts: localhost
  connection: local
  tasks:
    - name: Create group_vars Dir
      file: 
        path: "{{playbook_dir}}/inventories/{{machine_type}}/group_vars/"
        state: directory

    - name: "Create {{machine_type}} Dir"
      file: 
        path: "{{playbook_dir}}/inventories/{{machine_type}}/group_vars/"
        state: directory
        
    - name: Create Group Vars 
      setup_group_vars:
        mach_type: "{{machine_type}}"
        usr_src: "{{playbook_dir}}/files/{{machine_type}}.yml"
        default_src: "{{playbook_dir}}/files/defaults.yml"
      register: group_vars
     
    - name: Print Group Vars Message
      debug: var=group_vars
