---
- name: Setting up User Variables
  hosts: localhost
  connection: local
  tasks:      
    - name: Convert to JSOn
      set_fact:
          cp_user_vars: "{{do_vars|from_json}}"
      tags:
        - custom_vars          

    - name: "Create Servers and TPNodes Under Host Vars using Templates "
      template: src="{{playbook_dir}}/files/{{cloud_provider}}/{{item}}.j2" dest="{{playbook_dir}}/files/{{cloud_provider}}/{{item}}"
      with_items: 
            - "servers.yml"
            - "tpnodes.yml"          
      tags:
        - default_vars
        
    - name: Print All High Level Values
      debug: msg="All High Level {{cp_user_vars[c_p_indx|int][cloud_provider][0]}}"
      tags:
        - custom_vars
        
    - name: "Create Servers and TPNodes Files"
      template: src="{{playbook_dir}}/templates/{{cloud_provider}}/{{item}}.j2" dest="{{playbook_dir}}/files/{{cloud_provider}}/{{item}}"
      with_items: 
            - "servers.yml"
            - "tpnodes.yml"
      tags:
        - custom_vars            