---
# setup_topology.yml
# Author: muthukumarc
# Description: 
#    1. Setup SSH Key from Local to DigitalOcean
#    2. Create Digital Ocean Droplets based on servers.yml and tpnodes.yml passed by user using REST API
#    3. Create Hosts file for Servers and TP Nodes from In Memory Add Host 

- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars_files:
    - "{{playbook_dir}}/files/{{machine_type}}.yml"
  roles:
    - {role: setup.topology/digitalocean/upload_sshkey,tags: 'ssh-key' }
    - {role: setup.topology/digitalocean/, machine_type: "{{machine_type}}", username: "{{username}}",tags: 'create-droplet'}
    - {role: setup.topology/digitalocean/create_hosts,tags: 'hosts-file' }
