---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "{{playbook_dir}}/files/{{cloud_provider}}/{{machine_type}}.yml"
  tasks:
    - name: Upload SSH Key for Digital Ocean
      include_role:
            name: "setup.topology/{{cloud_provider}}/upload_sshkey"
      vars:
        do_token: "{{do_api_token}}"
      tags: ['ssh-key','digitalocean']
    
    - name: Create Instances based on Cloud Provider    
      include_role:
            name: "setup.topology/{{cloud_provider}}/"
      vars:
        machine_type: "{{machine_type}}"
        username: "{{username}}"
      tags: ['aws','digitalocean']

    - name: Create Hosts File based on Groups of Servers and TP Nodes   
      include_role:
            name: "setup.topology/{{cloud_provider}}/create_hosts"
      tags: ['aws','digitalocean']
