---
# setup_topology.yml
# Author: muthukumarc
# Description: 
#    1. Setup SSH Key from Local to DigitalOcean
#    2. Create Digital Ocean Droplets/Instances based on servers.yml and tpnodes.yml passed by user using REST API
#    3. Create Hosts file for Servers and TP Nodes from In Memory Add Host 

- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "{{playbook_dir}}/files/{{cloud_provider}}/{{machine_type}}.yml"
  tasks:
    - name: Upload SSH Key for Digital Ocean
      include_role:
            name: "setup.topology/{{cloud_provider}}/upload_sshkey"
      tags: ['ssh-key','digitalocean']
    
    - name: Create Instances based on Cloud Provider    
      include_role:
            name: "setup.topology/{{cloud_provider}}/"
      vars:
        machine_type: "{{machine_type}}"
        username: "{{username}}"
      tags: ['aws','digitalocean']

    - name: Create Hosts File based on Groups of Servers and TP Nodes   
      include_role:
            name: "setup.topology/{{cloud_provider}}/create_hosts"
      tags: ['aws','digitalocean']
