---
- hosts: localhost  
  vars_files:
    - "{{machine_type}}.yml"

  roles:
    - {role: setup.topology/upload_sshkey }
    - {role: setup.topology, machine_type: "{{machine_type}}"}
    - {role: setup.topology/create_hosts }
    