---
- hosts: localhost  
  tasks:
        - name: Update UI groovy file with versions
          setup_ui:
            snapshot_url: "{{item}}"
          with_items:
                - http://10.80.80.156/nexus/service/local/lucene/search?g=com.cleo.installers&a=Harmony&repositoryId=InstallerSnapshots
                - http://10.80.80.156/nexus/service/local/lucene/search?g=com.cleo.installers&a=Harmony&repositoryId=releases
          register: ui_res
          retries: 3
          delay: 5  
          until: ui_res|success          
          
        - name: Set Fact Release
          set_fact:
                relsnapVersions: []

        - name: Print UI Res
          set_fact:
                relsnapVersions: "{{ relsnapVersions }} + {{ item.msg }}"
          # when: item.msg |int| version_compare('5.4.1','>=')      
          with_items: "{{ui_res.results}}"
          
        # - name: Debug Versions
          # debug: msg="Ver:- {{relsnapVersions}}" 
          # when: relsnapVersions | version_compare('5.4.1','>=')
        - name: Set fact for relsnapVersions
          set_fact:
                relsnapVersions: "{{relsnapVersions|to_json}}"
                
        - debug: msg="{{ relsnapVersions  }}"                
                
        - name: Set SE Name Fact  
          set_fact:
                se_name: "{% raw -%} {{  self.name  }} {% endraw -%} "
        
        - name: Render Grooy UI Script
          template: src="{{playbook_dir}}/templates/ui_aws.groovy.j2" dest="{{playbook_dir}}/templates/ui_aws.groovy"
          register: ui_groovy_temp
        
        - name: Print Rendering Results
          debug: msg="Groovy UI results-{{ui_groovy_temp}}"         
