---
- hosts: localhost
  connection: local
  vars_files:      
     - "{{machine_type}}.yml"
     # - "vars/defaults.yml"
  roles:    
     - { role: "setup.group.vars" }
     
- hosts: "{{machine_type}}"
  connection: local
  vars_files:      
     - "{{machine_type}}.yml"
  roles:    
     - { role: "setup.host.vars" }