---
- hosts: "{{server_conf}}:{{tp_conf}}"
  roles:
     - { role: setup.testprofiles }
     - { role: setup.testprofiles/tests }
     # - { role: setup.testprofiles/pre_setup, grp_name: 'tpnodes-versalex' }
     # - { role: setup.testprofiles/pre_setup, grp_name: 'proxy', when: "'servers-versalex' in inventory_hostname" }     