---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - "{{playbook_dir}}/files/{{machine_type}}.yml"
  roles:
    - {role: setup.topology/digitalocean/upload_sshkey }
    - {role: setup.topology/digitalocean/, machine_type: "{{machine_type}}", username: "{{username}}"}
    - {role: setup.topology/digitalocean/create_hosts }
