---
- hosts: "{{server_conf}}:{{tp_conf}}"
  roles:
     - { role: setup.testprofiles/pre_setup, when: "'servers-versalex' in inventory_hostname" }
     - { role: setup.testprofiles/setup_tp }
     - { role: setup.testprofiles/setup_server }