---      
- hosts: "versalex:proxy"
  tasks:
    - name: Dataset from Servers-Versalex
      debug: msg="Print DataSet--{{hostvars['servers-versalex-1']['dataset']}}"
      
    - name: Setup FTP Client Args
      setup_ftp_client_args:
        host_ip: "{{ansible_ssh_host}}"
        server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        proxy_hosts: "{{ groups['servers-proxy'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        tp_hosts: "{{ groups['tpnodes-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
        dataset: "{{hostvars['servers-versalex-1']['dataset']}}"
      when: "'tpnodes-versalex' in inventory_hostname"
      register: ftp_client_args
      delegate_to: 127.0.0.1
      
    # - name: Test Rest1
      # test_rest1:
        # server_hosts: "{{ groups['servers-versalex'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"
      # register: rest_status
      # delegate_to: 127.0.0.1
      
    - name: Debug Rest Details
      debug: msg="Rest Details{{ftp_client_args}}"
      delegate_to: 127.0.0.1