---
- hosts: localhost  
  tasks:
    - name: Setup Listener Cer
      setup_listener_cert:
            host_ip: "10.20.101.157"
            cert_name: "VEX_LOCAL"
      register: listener_cert

    - name: Print Listerner Cert
      debug: msg="Listener Cert {{listener_cert}}"
            
    # - name: Convert Dataset Dictionary to Jmeter Arguments
      # jmeter_args:
        # jmx: "{{playbook_dir}}/files/SysTest_Linux_New.jmx"
        # dataset: {as2: {name: as2,'filespermin': '30',totalmins: 60,totalhosts: 2,threadcount: 10},ftp: {name: ftp,filespermin: 40,totalmins: 20,totalhosts: 1,threadcount: 10}} 
       # # dataset: {as2: {name: as2,filespermin: 30,totalmins: 60,totalhosts: 2,threadcount: 10}}      
      # delegate_to: 127.0.0.1
      # register: jmeter_arg
      
    # - name: Print jmeter arg
      # debug: msg="Jmeter arguments-{{jmeter_arg.meta}}"
      # delegate_to: 127.0.0.1

    # - name: Run Jmeter with Configs
      # shell: "{{jmeter_arg.meta}}"
      # environment:
         # PATH: "{{ ansible_env.PATH }}:/root/jmeter/apache-jmeter-3.3/bin" 
      # args:
         # executable: /bin/sh
      # register: jmeter_res
      # ignore_errors: yes
      # delegate_to: 127.0.0.1
      
    # - name: Print jmeter res
      # debug: msg="Jmeter arguments-{{jmeter_res}}"
      # delegate_to: 127.0.0.1
      
  # roles:
    # - { role: test.role,dataset: {as2: {name: as2,filespermin: 30,totalmins: 60,totalhosts: 2},ftp: {name: ftp,filespermin: 40,totalmins: 20,totalhosts: 1}} }