---
- hosts: localhost
  tasks:
      - name: Download Versalex Bin Package from Nexus  Central
        maven_artifact: 
           group_id: "com.cleo.installers"
           artifact_id: "Harmony"
           version: latest
           classifier: "linux64-jre18"
           extension: "bin"
           repository_url: "http://10.80.80.156/nexus/content/repositories/InstallerSnapshots/"
           dest: "/root/dload/"
           state: present
