---
- name: Setting Dictionary Name JMX Configs Versalex
  set_fact:
        jmx: "{{jmx_grp.value}}"

- name: "Edit versalexc.lax for JMX Configs File"
  lineinfile:
     create: no
     dest: "{{jmx.install_location}}{{jmx.dname}}c.lax"
     regexp: '^(lax.nl.java.option.additional=.*)'
     line: '\1 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port={{jmx.vex_jmx_port}} -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname={{ansible_ssh_host}}'
     state: present       
     backrefs: yes
  register: harmonyc_lax  
  
- name: "Edit setenv for JMX Configs karaf  File"
  lineinfile:
   create: no
   dest: "{{jmx.install_location}}core/bin/setenv"
   line: "{{item.line}}"
   state: present
  with_items:
     - {  line: 'export EXTRA_JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port={{jmx.karaf_jmx_port}} -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false" ', insertafter: EOF}
  register: karafc
