---
integrations:
  mysql:
    hostname: "servers-integrations-1"
    username: "root"
    maven_destfilename: "mysqltest24.jar"
    password: "testdocker"
    app_type: "mysql"
    maven_artifactid: "mysql-connector-java"
    node_ip: "dbsrv1"
    image_name: "testdockerfile"
    dbname: "mysql"
    app_srcdir: "/home/SystemTest/DockerFiles/"
    app_args: "MYSQL_ROOT_PASSWORD=testdocker"
    driver_str: "com.mysql.jdbc.Driver"
    app_port: "3306"
    use_docker_image: "true"
    maven_groupid: "mysql"
    maven_version: "5.1.24"
    docker: "true"
    image_tag: "latest"
    type: "db"
    port: "3306"
    app_destdir: "/root/DockerFile/"
