---
# tasks file for download.product
- block:     
    - name: User Passed Status {{status}}
      include_tasks: "start_stop.yml"
      with_dict: "{{ versalex | default({}) }}"
      loop_control:
         loop_var: vex_item
  rescue:
      - fail: msg="Versalex Service Status Change Faileed"