---
# defaults file for jmeter
jmeter_version: 3.3
jmeter_get_utl: "http://www-us.apache.org/dist//jmeter/binaries/apache-jmeter-{{jmeter_version}}.zip"
jmeter_dir: "/root/jmeter/"
share_dir: "/root/share/"
threadCount: 10
fileSizes: "5000 10000 20000 40000 80000 100000 200000 400000 500000 1000000"
jmeter_plugins_tst_url: "https://jmeter-plugins.org/files/packages/jpgc-tst-2.1.zip"
files_per_hour: "{{files_per_hr}}"