---
# tasks file for configure.product
- block:      
    - name: Download and Copy Systest Jar from Nexus to Remote Machine
      include_tasks: "{{role_path}}/tasks/jardload.yml"
      with_dict: "{{ versalex | default({}) }}"        
      loop_control:
         loop_var: systest_java
  rescue:
      - fail: msg="Download and Copy Systest Jar"    
