---
# tasks file for create.topology
- name: Create Inventory Dir
  file: 
    path: "{{playbook_dir}}/inventories/{{cloud_provider}}/{{machine_type}}/"
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1
  
- name: Create Hosts Inventory File
  template:
     src: create_hosts.j2
     dest: "{{playbook_dir}}/inventories/{{cloud_provider}}/{{machine_type}}/hosts"
  delegate_to: 127.0.0.1