---
# tasks for carrying out configs flow
  - name: Setting Dictionary Name for Proxy Inside
    set_fact:
       confvlp: "{{group_item.value}}"
    
  - include_vars:
        file: config.yml

  - name: Configure VLProxy File 
    include_tasks: create_properties.yml

  - name: Restart VersalEx Process 
    include_tasks: restart_versalex.yml