---
- name: Download artifact from Nexus
  local_action:
      module: get_url
      url: "{{ nexus_url }}&g={{ item.group }}&a={{ item.artifact }}&v={{ item.version }}&e={{ item.type }}&c={{ item.classifier }}"
      dest: "{{ download_location }}/properties-cipher.jar"
  run_once: true
  with_items:
    - { group: 'com.cleo.ep', artifact: 'properties-cipher', version: "{{ properties_cipher_version }}", type: 'jar', classifier: '' }
    
# Copy the properties-cipher jar into the installation
- name: Copy properties-cipher jar
  copy:
    src: "{{ download_location }}lib/properties-cipher.jar"
    dest: "{{ versalex.install_location }}properties-cipher.jar"

# Create a default.properties file from a template & copy to the installation
- name: Copy updated properties from template
  template:
    src: default.properties.j2
    dest: "{{ versalex.install_location }}/default.properties"

# Update encrypted properties in the installation
- name: Update encrypted properties
  shell: jre/bin/java -cp 'lib/*' com.cleo.VLProxy.PropertiesCipher
  args:
    chdir: "{{ versalex.install_location }}"
  register: properties_cipher_output


# Verify the versalex group serial numbers have been added to the VLProxy configuration
- name: Verify serial numbers
  assert:
    that:
      - "'{{ hostvars[item]['serialno'] }}' in properties_cipher_output.stdout"
    msg: "Serial number '{{ hostvars[item]['serialno'] }}' for {{ hostvars[item]['inventory_hostname'] }} not configured."
  with_items: "{{ groups[ 'versalex' ] }}"
  register: verify_serial
  until: not verify_serial |  failed
  retries: 3
  delay: 4
  ignore_errors: true