---
# - name: Download artifact from Nexus
  # local_action:
      # module: get_url
      # url: "{{ nexus_url }}&g={{ item.group }}&a={{ item.artifact }}&v={{ item.version }}&e={{ item.type }}&c={{ item.classifier }}"
      # dest: "{{ playbook_dir }}/files/properties-cipher.jar"
  # run_once: true
  # with_items:
    # - { group: 'com.cleo.ep', artifact: 'properties-cipher', version: "{{ properties_cipher_version }}", type: 'jar', classifier: '' }
  # delegate_to: 127.0.0.1
- name: "Create {{ansible_hostname}} Dir"
  file:
    path: "{{playbook_dir}}/files/{{ansible_hostname}}/"
    state: directory
  delegate_to: 127.0.0.1
  
- name: Download Properties Cipher Jar from Nexus Repo
  maven_artifact: 
        group_id: "{{item.group}}"
        artifact_id: "{{item.artifact}}"
        version: latest
        extension: "jar"
        repository_url: "{{confvlp.nexus_prod_repourl}}"
        dest: "{{playbook_dir}}/files/properties-cipher.jar"
        state: present
  run_once: true
  with_items:
    - { group: 'com.cleo.ep', artifact: 'properties-cipher', version: "latest", type: 'jar', classifier: '' }  
  delegate_to: 127.0.0.1 
  register: props_cipher
  retries: 3
  delay: 5
  until: props_cipher|success
    
# Copy the properties-cipher jar into the installation
- name: Copy properties-cipher jar
  copy:
    src: "{{ playbook_dir }}/files/properties-cipher.jar"
    dest: "{{ confvlp.install_location }}lib/properties-cipher.jar"
  
# Create a default.properties file from a template & copy to the installation
- name: Copy updated properties from template
  template:
    src: default.properties.j2
    dest: "{{ playbook_dir }}/files/{{ansible_hostname}}/default.properties"  
  delegate_to: 127.0.0.1
  
- name: Copy default properties to remote versalex instance
  copy:
    src: "{{ playbook_dir }}/files/{{ansible_hostname}}/default.properties"
    dest: "{{ confvlp.install_location }}default.properties"

# Update encrypted properties in the installation
- name: Update encrypted properties
  shell: jre/bin/java -cp $CLASSPATH com.cleo.VLProxy.PropertiesCipher
  environment:
     CLASSPATH: ":{{confvlp.install_location}}lib/*"  
  args:
    chdir: "{{ confvlp.install_location }}"
  register: properties_cipher_output

# Verify the versalex group serial numbers have been added to the VLProxy configuration
# - name: Verify serial numbers
  # assert:
    # that:
      # - "'{{ hostvars[item]['serialno'] }}' in properties_cipher_output.stdout"
    # msg: "Serial number '{{ hostvars[item]['serialno'] }}' for {{ hostvars[item]['inventory_hostname'] }} not configured."
  # with_items: "{{ groups[ 'versalex' ] }}"
  # register: verify_serial
  # until: not verify_serial |  failed
  # retries: 3
  # delay: 4
  # ignore_errors: true