---
- name: Initialize empty list
  set_fact:
    serial_list: []

- name: Add serial numbers to list
  set_fact:
    serial_list: "{{ serial_list }} + [ '{{ hostvars[item]['serialno'] }}' ]"
  with_items: "{{ groups[ 'versalex' ] | default([]) }}"
  
  
- name: Join the serial numbers into a comma separated list
  set_fact:
    serial_numbers_csv: "{{ serial_list | join(',') }}"
