---
# tasks file for setup.testprofiles
   # - name: Create Directory With Name Called Results
     # file: path="{{playbook_dir}}/results/{{role_path|basename}}" state=directory
     # delegate_to: 127.0.0.1
   # - name: Remove Machines Results File, If File Exists
     # file: path="{{playbook_dir}}/results/{{role_path|basename}}/machines.txt" state=absent
     # delegate_to: 127.0.0.1     
   # - name: Build Machines file with IPaddresses of Machines Created
     # lineinfile: dest="{{playbook_dir}}/results/{{role_path|basename}}/machines.txt"
                 # create=yes 
                 # line="{{inventory_hostname}}={{ansible_ssh_host}}"
                 # state=present              
     # delegate_to: 127.0.0.1
   # - name: Get OpenCSV Jar File to Remote Machine Versalex Install Location Lib Folder
     # get_url: url=http://central.maven.org/maven2/com/opencsv/opencsv/3.7/opencsv-3.7.jar dest="{{install_location}}lib/" mode=0777
     # when: vex_product is defined and vex_product != 'VLProxy'
     # ignore_errors: yes
   # - name: Copy SetupTestProfile Jar File to remote location
     # copy: src="{{checkout_dir}}/non-shipped/test/automation/systemtesting/setup_versalex/target/SetupTestProfile/SetupTestProfile.jar" dest="{{install_location}}"
     # when: vex_product is defined and vex_product != 'VLProxy'

   - name: Copy SetupOptions Jar File to remote location
     copy: src="/root/workspace/EFSS/non-shipped/test/automation/systemtesting/setup_versalex/target/systest_jars-0.1-SNAPSHOT.jar" dest="{{versalex.install_location}}/SetupTestProfile.jar"

   # - name: Copy SetupSchedule Jar File to remote location
     # copy: src="/root/workspace/EFSS/non-shipped/test/automation/systemtesting/setup_versalex/target/systest_jars-0.1-SNAPSHOT.jar" dest="{{versalex.install_location}}/SetupSchedule.jar"

   # - name: Copy SetupSchedule Jar File to remote location
     # copy: src="{{checkout_dir}}/non-shipped/test/automation/systemtesting/setup_versalex/target/SetupSchedule/SetupSchedule.jar" dest="{{install_location}}"
     # when: vex_product is defined and vex_product != 'VLProxy'
   # - name: Copy Test Profile CSV File to remote location
     # copy: src="{{testprofile_csvpath}}" dest="{{install_location}}" 
     # when: vex_product is defined and vex_product != 'VLProxy'
   # - name: Copy Machines File with IP Address  to remote location
     # copy: src="{{playbook_dir}}/results/{{role_path|basename}}/machines.txt" dest="{{install_location}}"
     # when: vex_product is defined and vex_product != 'VLProxy'
   - name: Install RSYNC packages
     yum: name=rsync state=present
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' and versalex.name is defined and versalex.name != 'VLProxy'     
