---
# tasks for carrying out configs flow
      - name: Setting Dictionary Name for Proxy Inside
        set_fact:
           versalex: "{{group_item.value}}"
        
      - name: Install CentOS Related Dependencies 
        include: centos.yml
        when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
        
      - name: Install Debian Related Dependencies
        include: debian.yml
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
        
      - name: Configure VersalEx Product
        include: configure_versalex.yml
        when: "'versalex' in subtype"
        
      - name: Configure Shares in Server Nodes
        include: configure_server_share.yml
        when: "'versalex' in subtype and versalex.server_share_path is defined"
        
      - name: Configure Shares in Client Nodes
        include: configure_client_share.yml
        when: "'versalex' in subtype and versalex.server_share_path is not defined"
      
      - name: Create VLProxy File for configuration
        include: create_vlproxyfile.yml
        when: "'versalex' in subtype"

      - name: Configure VLProxy File 
        include: configure_vlproxy.yml
        when:  "'proxy' in subtype"

      - name: Restart VersalEx Process 
        include: restart_versalex.yml