---
# tasks file for install.apps
- name: Install Unzip package for running bin file in debian
  apt: name=unzip state=present

- name: "Install python-lxml packages(required for maven_artifact) on Debian based (Ubuntu)  machines"
  apt: name=python-lxml state=latest
  retries: 3
  delay: 5  
  until: install_lxml|success
  register: install_lxml
  
- name: Install RNG-tools required for Random Number Generation using APT
  apt: name=rng-tools state=present
  
- name: "Install python2.7 in deian OS if python 3 is default"
  include: "install_debian_py27.yml"
  when: ansible_distribution_version | int >= 15
    
- name: Run RNGD Service using Debian
  service: name=rng-tools state=restarted
  register: rngd_status
  retries: 3
  delay: 10
  until: rngd_status|success

- name: Update APT repositories
  apt: update_cache=yes
- name: Make sure apt-transport-https is installed
  apt:
    pkg: "apt-transport-https"
    state: installed
  register: apthttps
  until: "'failed' not in apthttps"
  retries: 3
  delay: 10
- name: Add Docker repository key
  apt_key:
    id: "36A1D7869245C8950F966E92D8576A8BA88D21E9"
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present
  register: dockerrepokey
  until: "'failed' not in dockerrepokey"
  retries: 3
  delay: 10        
- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb http://get.docker.io/ubuntu docker main"
    update_cache: yes
    state: present
  register: aptrepocache
  until: "'failed' not in aptrepocache"
  retries: 3
  delay: 10
- name: Install lxc-docker
  apt:
    pkg: "lxc-docker"
    state: installed
  register: lxcdocker
  until: "'failed' not in lxcdocker"
  retries: 3
  delay: 10
- name: Install pip
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - python-pip
  register: pipinstall
  until: "'failed' not in pipinstall"
  retries: 3
  delay: 10
- name: Install Docker-py
  pip:
    name: docker-py
  register: dockerpy
  until: "'failed' not in dockerpy"
  retries: 3
  delay: 10
- name: Check Docker is Running
  service: name=docker state=running
  register: dockersvce
  until: "'failed' not in dockersvce"
  retries: 3
  delay: 10  