---
# tasks file for setup.testprofiles
- block:
   - name: Setting group name if Proxy defined
     set_fact:        
       grp_name: 'proxy'
     when: groups['proxy'] is defined
     delegate_to: 127.0.0.1

   - name: Setting group name if Proxy not defined
     set_fact:        
       grp_name: 'tpnodes-versalex'
     when: groups['proxy'] is not defined
     delegate_to: 127.0.0.1
     
   - name: Setting Node Count for TPNodes
     set_fact:        
       vex_count: "{{ groups['tpnodes-versalex'] | length | int}}"
     delegate_to: 127.0.0.1
     
   - name: TPSide Dataset setup
     template: src=setup_tp_testprofile.j2 dest="{{playbook_dir}}/dataset/{{inventory_hostname}}-{{grp_name}}.yml"
     delegate_to: 127.0.0.1   
        
   - name: Printing for Debug
     debug: msg="Done with TP DataSet "
  
- rescue:
   - fail: msg="Setup Test Profile Module Failed"     