---
# tasks file for pre_setup
- block:
   - name: Setting Node Count for TPNodes
     set_fact:        
       vex_count: "{{ groups[grp_name] | length | int}}"
     delegate_to: 127.0.0.1
     
   - name: Install RSYNC packages
     yum: name=rsync state=present
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

   - name: Install RSYNC packages on Local Host machine
     yum: name=rsync state=present     
     register: rngd_status
     retries: 3
     delay: 10
     until: rngd_status|success
     delegate_to: 127.0.0.1     
     
   # - name: Deletes Files in Dataset directory
     # file: 
        # path: "{{playbook_dir}}/dataset/"
        # state: absent    
     # delegate_to: 127.0.0.1
     
   - name: Creates Map Directory
     file:
       path: "{{playbook_dir}}/dataset/"
       state: directory
       mode: 0777
     delegate_to: 127.0.0.1

- rescue:
   - fail: msg="Setup Test Profile Module Failed" 
