---
hardware:
   versalex:           
      - name: 
        ram_size: 1gb
        region: nyc1
        image_name: "centos-6-x64"
        qty: 
        
   proxy:           
      - name: 
        ram_size: 1gb
        region: nyc1
        image_name: "centos-6-x64"
        qty: 
   shares:           
      - name: share
        ram_size: 1gb
        region: nyc1
        image_name: "centos-6-x64"
        qty: 1          
software:
   versalex:
      - name: 
        version: gag
        install_location: "/root/Harmony/"
        vex_jmx_port: 3022
   integrations:
      - name: 
        version: "mysql:latest"
   proxy:
      - name: vlproxy
        version: 5.4.1-SNAPSHOT
        install_location: "/root/VLProxy/"
        vex_jmx_port: 3022
   shares:           
      - name: share
        server_share_path: "/root/share/"   
dataset:
   versalex:
      - name: as2
        total: 20
        schedule_actions: true  
      - name: ftp
        total: 20
        schedule_actions: true         