---
# tasks file for download.product
- block:     
   - name: Install lxml using pip Locally in Container
     pip: 
        name: lxml
     delegate_to: 127.0.0.1
     
   - name: Download Product Role with Versalex
     include_tasks: "download_versalex.yml"
     with_dict: "{{ prod_key | default({}) }}"
     loop_control:
        loop_var: dload_group
  rescue:
      - fail: msg="Install Product Download Tasks failed"