---
# tasks for carrying out configs flow
 - block:
      - name: Setting Dictionary Name Config Versalex
        set_fact:
           confvex: "{{config_vex.value}}"     
        
      - name: Configure VersalEx Product
        include_tasks: configure_versalex.yml
        # when: "'versalex' in subtype"
 
      # - name: Restart VersalEx Process 
        # include_tasks: restart_versalex.yml
   rescue:
      - fail: msg="Configure Applications failed"
   