---
# - name: "Calling Heap Mem Configuration"
  # include: configure_heap_jmx.yml
  
- name: "Edit Versalex.lax  File"
  lineinfile:
     create: no
     dest: "{{versalex.install_location}}{{versalex.dname}}c.lax"
     line: "-Xms{{versalex.vex_heapmem_min}} -Xmx{{versalex.vex_heapmem_max}} -XX:+HeapDumpOnOutOfMemoryError -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port={{versalex.vex_jmx_port}} -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname={{ansible_ssh_host}}"
     state: present       
     insertafter: EOF
  register: harmonyc_lax  
  
- name: "Edit setenv for karaf  File"
  lineinfile:
   create: no
   dest: "{{versalex.install_location}}core/bin/setenv"
   line: "{{item.line}}"
   state: present
  with_items:
     - {  line: 'export JAVA_MIN_MEM={{versalex.karaf_heapmem_min}}', insertafter: EOF}
     - {  line: 'export JAVA_MAX_MEM={{versalex.karaf_heapmem_max}}', insertafter: EOF}
     - {  line: 'export EXTRA_JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port={{versalex.karaf_jmx_port}} -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false" ', insertafter: EOF}
  register: karafc
  
- name: Copy SetupOptions Jar File to remote location
  copy: src="{{playbook_dir}}/lib/" dest="{{versalex.install_location}}lib/"

- name: Download DB artifact from Maven Central
  maven_artifact: 
    group_id: "{{item.value.maven_groupid}}"
    artifact_id: "{{item.value.maven_artifactid}}"
    version: "{{item.value.maven_version}}"
    dest: "{{versalex.install_location}}lib/ext/{{item.value.maven_destfilename}}"  
  when: "'db' in item.value.type"  
  with_dict: "{{ integrations | default({}) }}"
  register: mysql_download
  ignore_errors: yes

- name: Configure DB in Remote Machines
  shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{versalex.dname}}" "{{versalex.install_location}}" "DB" "jdbc:{{item.value.app_type}}://{{hostvars[item.value.hostname]['ansible_eth0']['ipv4']['address']}}:{{item.value.port}}/{{item.value.dbname}}" "{{item.value.driver_str}}" "{{item.value.username}}" "{{item.value.password}}" 1 "jdbc:{{item.value.app_type}}://{{hostvars[item.value.hostname]['ansible_eth0']['ipv4']['address']}}:{{item.value.port}}/{{item.value.dbname}}"
  environment:
     CLASSPATH: ":{{versalex.install_location}}*.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
  args:
     chdir: "{{versalex.install_location}}"
  when: "'db' in item.value.type"
  with_dict: "{{ integrations | default({}) }}"  
  register: db_config
  retries: 3
  delay: 5  
  until: db_config|success
  
- name: Configure PROXY in Remote Machines on VersalEx Products
  shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{versalex.dname}}" "{{versalex.install_location}}" "PROXY" "{{item.value.type}}" "{{hostvars[item.value.hostname]['ansible_eth0']['ipv4']['address'] }}" "{{item.value.port}}" "{{item.value.revfwdproxy}}"
  environment:
     CLASSPATH: ":{{versalex.install_location}}SetupOptions.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
  args:
     chdir: "{{versalex.install_location}}"
  with_dict: "{{ proxy | default({}) }}"         
  register: proxy_config
  retries: 3
  delay: 5  
  until: proxy_config|success

- name: Configure LDAP in Remote Machines
  shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{versalex.vex_product}}" "{{versalex.install_location}}" "LDAP" "{{item.value.type}}" "{{item.value.host}}" "{{item.value.port}}" "{{item.value.secuirtymode}}" "{{item.value.value.basedn}}" "{{item.value.username}}" "{{item.value.fullnameattrib}}" "{{item.value.homedirattrib}}" "{{item.value.emailattrib}}" "{{item.value.searchfilter}}" "{{item.value.usernameattrib}}" "zzzzers"
  environment:
     CLASSPATH: ":{{versalex.install_location}}SetupOptions.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
  args:
     chdir: "{{versalex.install_location}}"
  when: "'ldap' in item.value.type"     
  with_dict: "{{ integrations | default({}) }}"
  register: ldap_config
  retries: 3
  delay: 5  
  until: ldap_config|success
 
