---
- name: Download DB artifact from Maven Central
  maven_artifact: 
    group_id: "{{item.value.maven_groupid}}"
    artifact_id: "{{item.value.maven_artifactid}}"
    version: "{{item.value.maven_version}}"
    dest: "{{confvex.install_location}}lib/ext/"  
  when: "'db' in item.value.type"  
  with_dict: "{{ integrations | default({}) }}"
  register: mysql_download
  ignore_errors: yes

- name: "Restart VersalEx Process (Inside Versalex)" 
  include: restart_versalex.yml

        
- name: Extract DB IP 
  set_fact:
    db_ip: "{{hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
  with_items: "{{groups['integrations'] |default({})}}"  
  delegate_to: 127.0.0.1

- name: Configure DB in Remote Machines
  shell: jre/bin/java -cp "$CLASSPATH" com.cleo.systest.SetupOptions "{{confvex.dname}}" "{{confvex.install_location}}" "DB" "jdbc:{{item.value.app_type}}://{{db_ip}}:{{item.value.port}}/{{item.value.dbname}}" "{{item.value.driver_str}}" "{{item.value.username}}" "{{item.value.password}}" 1 "jdbc:{{item.value.app_type}}://{{db_ip}}:{{item.value.port}}/{{item.value.dbname}}"
  environment:
     CLASSPATH: ":{{confvex.install_location}}lib/versalex_setup-latest.jar:{{confvex.install_location}}lib/*:{{confvex.install_location}}lib/help/*:{{confvex.install_location}}lib/hibernate/*:{{confvex.install_location}}lib/secureshare/*:{{confvex.install_location}}webserver/AjaxSwing/lib/*:{{confvex.install_location}}lib/json/*"
  args:
     chdir: "{{confvex.install_location}}"
  when: "'db' in item.value.type"
  with_dict: "{{ integrations | default({}) }}"  
  register: db_config
  retries: 2
  delay: 5  
  until: db_config|success

- name: Extract Proxy IP 
  set_fact:
    proxy_ip: "{{hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
  with_items: "{{groups['proxy']  |default({})}}"  

- name: Configure PROXY in Remote Machines on VersalEx Products
  shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{confvex.dname}}" "{{confvex.install_location}}" "PROXY" "{{item.2.type}}" "{{hostvars[item.0]['ansible_eth0']['ipv4']['address']}}" "{{item.2.port}}" "{{item.2.revfwdproxy}}"
  environment:
     CLASSPATH: ":{{confvex.install_location}}versalex_setup-latest.jar:{{confvex.install_location}}lib/*:{{confvex.install_location}}lib/help/*:{{confvex.install_location}}lib/hibernate/*:{{confvex.install_location}}lib/secureshare/*:{{confvex.install_location}}webserver/AjaxSwing/lib/*:{{confvex.install_location}}lib/json/*"
  args:
     chdir: "{{confvex.install_location}}"
  # with_dict: "{{ proxy | default({}) }}"
  with_nested:       
       - "{{groups['proxy']  |default({})}}"
       - "{{ proxy | dictsort }}"
  register: proxy_config
  when: proxy is defined
  retries: 3
  delay: 5  
  until: proxy_config|success

- name: Configure LDAP in Remote Machines
  shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{confvex.vex_product}}" "{{confvex.install_location}}" "LDAP" "{{item.value.type}}" "{{item.value.host}}" "{{item.value.port}}" "{{item.value.secuirtymode}}" "{{item.value.value.basedn}}" "{{item.value.username}}" "{{item.value.fullnameattrib}}" "{{item.value.homedirattrib}}" "{{item.value.emailattrib}}" "{{item.value.searchfilter}}" "{{item.value.usernameattrib}}" "zzzzers"
  environment:
     CLASSPATH: ":{{confvex.install_location}}SetupOptions.jar:{{confvex.install_location}}lib/*:{{confvex.install_location}}lib/help/*:{{confvex.install_location}}lib/hibernate/*:{{confvex.install_location}}lib/secureshare/*:{{confvex.install_location}}webserver/AjaxSwing/lib/*:{{confvex.install_location}}lib/json/*"
  args:
     chdir: "{{confvex.install_location}}"
  when: "'ldap' in item.value.type"     
  with_dict: "{{ integrations | default({}) }}"
  register: ldap_config
  retries: 3
  delay: 5  
  until: ldap_config|success