---
# tasks for carrying out configs flow
 - block:
      - name: Setting Dictionary Name Config Versalex
        set_fact:
           versalex: "{{group_item.value}}"

      - name: Download SysTest Jar from Nexus Repo
        maven_artifact: 
                group_id: "{{versalex.nexus_systest_groupid}}"
                artifact_id: "{{versalex.nexus_systest_artifactid}}"
                version: latest
                extension: "jar"
                repository_url: "{{versalex.nexus_systest_repourl}}"
                dest: "{{playbook_dir}}/library/"
                state: present
        run_once: true
        delegate_to: 127.0.0.1        
        
      - name: Configure VersalEx Product
        include: configure_versalex.yml
        # when: "'versalex' in subtype"
 
      - name: Restart VersalEx Process 
        include: restart_versalex.yml
   rescue:
      - fail: msg="Configure Applications failed"
   