   - name: Creates Shares Destination Path Directory
     file: path="{{versalex.server_share_path}}" state=directory
     # when: versalex.server_share_path is defined     

   - name: "Add Dir Entry to /etc/exports file"
     lineinfile:
        create: yes
        dest: "/etc/exports"
        line: "{{versalex.server_share_path}}  *(rw,sync,no_root_squash,no_subtree_check)"
        state: present
        insertafter: EOF
     # when: versalex.server_share_path is defined     
        
   - name: Configure Exportfs in Remote Machines
     shell: "exportfs -a"     
     register: export_results
     # when: versalex.server_share_path is defined     
     
   - name: Ensure NFS and RPCBind service restarted
     service: name="{{ item }}" state=restarted enabled=yes
     with_items:
        - rpcbind
        - nfslock
        - nfs
     # when: versalex.server_share_path is defined     
        
   - name: Copy SetupOptions Jar File to remote location
     copy: src="{{playbook_dir}}/library/" dest="{{versalex.install_location}}lib/"
     # when: versalex.server_share_path is defined     
   
   - name: Configure Shares in Remote Machines
     shell: jre/bin/java -cp $CLASSPATH com.cleo.systest.SetupOptions "{{versalex.name}}" "{{versalex.install_location}}" "SHARE" "{{versalex.server_custom_macro}}"
     environment:
       CLASSPATH: ":{{versalex.install_location}}*.jar:{{versalex.install_location}}lib/*:{{versalex.install_location}}lib/help/*:{{versalex.install_location}}lib/hibernate/*:{{versalex.install_location}}lib/secureshare/*:{{versalex.install_location}}webserver/AjaxSwing/lib/*:{{versalex.install_location}}lib/json/*"
     args:
       chdir: "{{versalex.install_location}}"
     # with_dict: "{{configure_apps['nfs_server_shares'] | default({}) }}"
     # when: (versalex.name != 'VLProxy' and versalex.server_share_path is defined)
     register: shares_config
     retries: 3
     delay: 5  
     until: shares_config|success