---
# tasks file for configure.product
- block:      
    - name: Include Configure Product Role with Versalex
      include_tasks: "config_flow.yml"
      with_dict: "{{ versalex | default({}) }}"        
      when: "'versalex' in subtype"
      loop_control:
         loop_var: group_item
  rescue:
      - fail: msg="Configure Product Module failed"