---
# tasks file for configure.product
- block:
      # - name: Include Node Specific Variables
        # include_vars: "{{inventory_hostname}}.yml"
        # ignore_errors: yes
      - name: Include Configure Product Role with Versalex
        include: "config_flow.yml"
          #debug: msg="TestType Key- {{item.key}} Test Val -{{item.value}}"      
        with_dict: "{{ versalex | default({}) }}"
        # when: versalex is defined
        when: "'versalex' in subtype"
        loop_control:
           loop_var: group_item
        tags: centos
           
      # - name: Include Configure Product Role with Proxy
        # include: "config_flow.yml"
          # #debug: msg="TestType Key- {{item.key}} Test Val -{{item.value}}"      
        # with_dict: "{{ proxy | default({}) }}"
        # # when: versalex is defined
        # when: "'proxy' in subtype"
        # loop_control:
           # loop_var: group_item             
  rescue:
      - fail: msg="Configure Product Module failed"