---
- name: Shutdown VersalEx Process ..after LDAP and DB Configs
  shell: "{{item}}"
  args:
    chdir: "{{versalex.install_location}}"
  with_items:
    - ./{{versalex.dname}}d stop
  register: stopvexstatus
  
- name: Stop Results
  debug: msg="Stop Resultls {{stopvexstatus}} versalex_artifactid {{versalex.dname}}"
  
- name: Wait for port 5080 to get Stopped
  wait_for: port=5080 delay=10 state=stopped
  
- name: Start VersalEx Product Daemon   
  shell: "{{item}}"
  args:
    chdir: "{{versalex.install_location}}"
  with_items:
    - ./{{versalex.dname}}d start
  register: startvexstatus