---
# tasks file for create.topology
  - name: Replace Ansible Cfg Files
    replace:
        path: '/etc/ansible/ansible.cfg'
        regexp: "{{item.replace_from}}"
        replace: "{{item.replace_to}}"
        backup: yes
    with_items:
        - {replace_from: '#host_key_checking = False', replace_to: 'host_key_checking = False'}
        - {replace_from: '#hash_behaviour = replace',replace_to: 'hash_behaviour = merge'}
    register: replace_status
    
  - name: Generate and upload sshkeys to digitalocean
    include_tasks: "upload_sshkey.yml"